@echo off
REM ============================================================
REM  TPE Bridge - Installeur Windows TOUT-EN-UN (mini-PC des salons)
REM
REM  Fichier UNIQUE et autonome : aucun autre fichier necessaire a cote.
REM  Il contient ses propres fichiers embarques (encodes) et les
REM  extrait lui-meme lors de l'installation.
REM
REM  Utilisation : clic droit sur ce fichier -^> "Executer en tant
REM  qu'administrateur". C'est tout.
REM
REM  Ce que fait ce script :
REM   1. Verifie/installe Node.js (silencieux, via winget)
REM   2. Arrete une eventuelle instance du pont deja en cours
REM   3. Extrait ses fichiers embarques dans C:\TPE-Bridge
REM   4. Cree une regle de pare-feu entrante (TPE / impression locale)
REM   5. Depose un lanceur dans le dossier Demarrage de Windows : le pont
REM      demarre tout seul, sans fenetre, a chaque ouverture de session
REM      (et se relance seul apres 5 s s'il s'arrete - voir startBridge)
REM   6. Lance l'assistant de configuration (fenetre graphique,
REM      pas de terminal a manipuler)
REM ============================================================

setlocal enabledelayedexpansion

echo.
echo ============================================================
echo    TPE Bridge - Installation pour le salon
echo ============================================================
echo.

REM --- Verifier les droits administrateur ---
net session >nul 2>&1
if %errorLevel% neq 0 (
    echo [!] Ce script doit etre lance en tant qu'administrateur.
    echo     Clic droit sur ce fichier -^> "Executer en tant qu'administrateur"
    pause
    exit /b 1
)

set BRIDGE_DIR=C:\TPE-Bridge
set TMP_DIR=%TEMP%\tpe-bridge-install

if not exist "%TMP_DIR%" mkdir "%TMP_DIR%" >nul 2>&1

REM --- 1. Node.js ---
where node >nul 2>nul
if %errorLevel% equ 0 (
    echo [OK] Node.js deja installe :
    node --version
) else (
    echo [..] Installation de Node.js...
    winget install OpenJS.NodeJS.LTS --silent --accept-package-agreements --accept-source-agreements
    if %errorLevel% neq 0 (
        echo [!] winget a echoue. Installez Node.js manuellement depuis
        echo     https://nodejs.org puis relancez ce script.
        pause
        exit /b 1
    )
    echo [OK] Node.js installe.
    set "PATH=%PATH%;C:\Program Files\nodejs"
)

REM --- 2. Arreter toute instance du pont deja en cours (evite les fichiers
REM        verrouilles lors de l'extraction ci-dessous)
echo [..] Arret d'une eventuelle instance du pont deja en cours...
powershell.exe -NoProfile -Command "Get-CimInstance Win32_Process -Filter \"Name='node.exe'\" -ErrorAction SilentlyContinue | Where-Object { $_.CommandLine -like '*tpe-bridge-win.js*' -or $_.CommandLine -like '*tpe-bridge.js*' } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }" >nul 2>&1
timeout /t 1 /nobreak >nul

REM --- 3. Extraire les fichiers embarques dans %BRIDGE_DIR% ---
echo [..] Installation des fichiers dans %BRIDGE_DIR%...
if not exist "%BRIDGE_DIR%" mkdir "%BRIDGE_DIR%"
call :extract_payload TPE_BRIDGE_CORE "%BRIDGE_DIR%\tpe-bridge.js"
call :extract_payload TPE_BRIDGE_WIN "%BRIDGE_DIR%\tpe-bridge-win.js"
call :extract_payload CONFIG_WIZARD "%BRIDGE_DIR%\config-wizard.ps1"
call :extract_payload CONFIGURER_BAT "%BRIDGE_DIR%\Configurer.bat"
call :extract_payload RUN_HIDDEN_VBS "%BRIDGE_DIR%\run-hidden.vbs"
if not exist "%BRIDGE_DIR%\tpe-bridge.js" (
    echo [!] Echec de l'extraction des fichiers. Contactez le support.
    pause
    exit /b 1
)
echo [OK] Fichiers installes.

REM --- 4. Pare-feu : autoriser le pont en reseau local (TPE, impression)
echo [..] Configuration du pare-feu...
netsh advfirewall firewall delete rule name="TPE Bridge" >nul 2>&1
netsh advfirewall firewall add rule name="TPE Bridge" dir=in action=allow program="C:\Program Files\nodejs\node.exe" enable=yes profile=any >nul 2>&1
echo [OK] Pare-feu configure.

REM --- 5. Demarrage automatique : le lanceur invisible est depose dans le
REM        dossier Demarrage de l'utilisateur, donc lance a chaque ouverture
REM        de session Windows. (L'ancienne methode - tache planifiee - ne
REM        fonctionnait jamais : la commande schtasks etait rejetee car une
REM        option y figurait deux fois, et l'erreur etait masquee.)
echo [..] Creation du demarrage automatique...
schtasks /Delete /TN "TPE-Bridge" /F >nul 2>&1
set "STARTUP_DIR=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
if not exist "%STARTUP_DIR%" mkdir "%STARTUP_DIR%" >nul 2>&1
copy /Y "%BRIDGE_DIR%\run-hidden.vbs" "%STARTUP_DIR%\TPE-Bridge.vbs" >nul 2>&1
REM Lien tpebridge://start (utilise par le bouton "Demarrer le pont" du
REM dashboard) : declare a Windows dans la ruche de l'utilisateur, sans droits
REM supplementaires. La commande ne recoit AUCUN argument venant du lien, donc
REM une page web ne peut rien faire d'autre que demander de lancer le pont.
reg add "HKCU\Software\Classes\tpebridge" /ve /t REG_SZ /d "URL:TPE Bridge" /f >nul 2>&1
reg add "HKCU\Software\Classes\tpebridge" /v "URL Protocol" /t REG_SZ /d "" /f >nul 2>&1
reg add "HKCU\Software\Classes\tpebridge\shell\open\command" /ve /t REG_SZ /d "wscript.exe \"%BRIDGE_DIR%\run-hidden.vbs\" bouton" /f >nul 2>&1
if exist "%STARTUP_DIR%\TPE-Bridge.vbs" (
    echo [OK] Demarrage automatique configure.
) else (
    echo [!] Demarrage automatique non configure - le pont devra etre relance a la main
    echo     apres chaque redemarrage : double-clic sur %BRIDGE_DIR%\run-hidden.vbs
)

REM --- 6. Configuration (formulaire graphique - pas de terminal a manipuler)
echo.
echo ============================================================
echo    Derniere etape : une fenetre de configuration va s'ouvrir
echo ============================================================
echo.
cd /d "%BRIDGE_DIR%"
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%BRIDGE_DIR%\config-wizard.ps1"
if not exist "%APPDATA%\TPE-Bridge\config.json" (
    echo.
    echo [!] Configuration annulee ou non terminee.
    echo     Relancez ce programme pour reessayer, ou double-cliquez sur
    echo     %BRIDGE_DIR%\config-wizard.ps1 pour ouvrir juste le formulaire.
    pause
    exit /b 1
)
echo [OK] Configuration enregistree.
echo.
wscript.exe "%BRIDGE_DIR%\run-hidden.vbs" installeur

echo.
echo ============================================================
echo    Installation terminee !
echo    Le pont tourne maintenant en arriere-plan, sans fenetre
echo    visible - c'est normal, il n'y a rien d'autre a faire.
echo    Il demarrera aussi automatiquement a chaque demarrage.
echo ============================================================
rd /s /q "%TMP_DIR%" >nul 2>&1
pause
exit /b 0

REM ============================================================
REM  Sous-routine : extrait un bloc de donnees embarque plus bas
REM  dans ce meme fichier (entre :NOM_BEGIN et :NOM_END) vers un
REM  fichier temporaire .b64, puis le decode avec certutil.
REM  %1 = nom du marqueur   %2 = fichier de destination final
REM ============================================================
:extract_payload
setlocal enabledelayedexpansion
set "B64FILE=%TMP_DIR%\%~1.b64"
if exist "%B64FILE%" del /f /q "%B64FILE%" >nul 2>&1
set "CAPTURE=0"
for /f "usebackq delims=" %%L in ("%~f0") do (
    if "!CAPTURE!"=="1" (
        if "%%L"==":%~1_END" (
            set "CAPTURE=0"
        ) else (
            >>"%B64FILE%" echo(%%L
        )
    ) else (
        if "%%L"==":%~1_BEGIN" set "CAPTURE=1"
    )
)
certutil -decode -f "%B64FILE%" "%~2" >nul
endlocal
exit /b

REM ============================================================
REM  Donnees embarquees ci-dessous (ne pas modifier a la main).
REM  Le script s'arrete toujours avant d'atteindre cette zone -
REM  elle n'est lue que comme donnees par extract_payload.
REM ============================================================
:TPE_BRIDGE_CORE_BEGIN
-----BEGIN CERTIFICATE-----
IyEvdXNyL2Jpbi9lbnYgbm9kZQovKioKICogUG9udCBsb2NhbCBjYWlzc2UgPC0+
IFRQRSAocHJvdG9jb2xlIENvbmNlcnQgdjMgSVApLgogKgogKiBQUk9CTMOITUUg
UsOJU09MVSA6IGwnYXBwIGRlIGNhaXNzZSBlc3QgaMOpYmVyZ8OpZSBlbiBsaWdu
ZSAoeENsb3VkKSwgbWFpcwogKiBsZSBUUEUgdml0IHN1ciBsZSByw6lzZWF1IGxv
Y2FsIGR1IHNhbG9uIChleC4gMTkyLjE2OC4xLjEyNSkuIFVuIHNlcnZldXIKICog
ZGlzdGFudCBuZSBwZXV0IEpBTUFJUyBqb2luZHJlIHVuZSBJUCBwcml2w6llIC0g
bGUgcGFpZW1lbnQgY2FydGUKICogw6ljaG91YWl0IGRvbmMgaW52YXJpYWJsZW1l
bnQuIENlIHBldGl0IHBvbnQgdG91cm5lIHN1ciBuJ2ltcG9ydGUgcXVlbAogKiBv
cmRpbmF0ZXVyIGR1IHNhbG9uIChQQyBkZSBjYWlzc2UsIG1pbmktUEMsIG3Dqm1l
IHVuIFJhc3BiZXJyeSBQaSkgOgogKiBsZSBuYXZpZ2F0ZXVyIGRlIGxhIGNhaXNz
ZSBsdWkgZMOpbMOoZ3VlIGwnZW52b2ksIGV0IGx1aSBwYXJsZSBhdSBUUEUKICog
ZW4gVENQIGxvY2FsLgogKgogKiBBVUNVTkUgRMOJUEVOREFOQ0UgOiBOb2RlLmpz
ID49IDE4IHN1ZmZpdCAoZmV0Y2ggZXQgaHR0cCBuYXRpZnMpLgogKgogKiBVc2Fn
ZSA6CiAqICAgbm9kZSB0cGUtYnJpZGdlLmpzIC0tdHBlIDE5Mi4xNjguMS4xMjUg
Wy0tcG9ydCA4ODg4XSBbLS1saXN0ZW4gNzc4OF0gWy0tcG9zIDJdCiAqCiAqICAg
LS10cGUgPGlwPiAgICAgIEFkcmVzc2UgSVAgZHUgdGVybWluYWwgKG9ibGlnYXRv
aXJlIC0gY2VsbGUgZHUgdGlja2V0CiAqICAgICAgICAgICAgICAgICAgIGRlIGNv
bmZpZywgZXguIDE5Mi4xNjguMS4xMjUpCiAqICAgLS1wb3J0IDxuPiAgICAgIFBv
cnQgZCfDqWNvdXRlIENvbmNlcnQgZHUgVFBFIChkw6lmYXV0IDogODg4OCkKICog
ICAtLWxpc3RlbiA8bj4gICAgUG9ydCBIVFRQIGR1IHBvbnQgKGTDqWZhdXQgOiA3
Nzg4KQogKiAgIC0tcG9zIDxuPiAgICAgICBOdW3DqXJvIGRlIGNhaXNzZSAoZMOp
ZmF1dCA6IGNlbHVpIGR1IHRpY2tldCwgZXguIDIpCiAqCiAqIExhIGNhaXNzZSAo
UsOpZ2xhZ2VzID4gVGVybWluYWwgZGUgcGFpZW1lbnQgPiBQb250IGxvY2FsKSBk
b2l0IHBvaW50ZXIKICogdmVycyBodHRwOi8vPGlwLWRlLWNldC1vcmRpbmF0ZXVy
Pjo3Nzg4CiAqCiAqIEVuZHBvaW50cyA6CiAqICAgR0VUICAvaGVhbHRoICAgLT4g
eyBvazogdHJ1ZSB9ICh0ZXN0IGRlIGNvbW11bmljYXRpb24gZGVwdWlzIGxhIGNh
aXNzZSkKICogICBQT1NUIC9jaGFyZ2UgICAtPiB7IGFtb3VudF9jZW50czogMTUw
MCB9IC0gZW52b2llIGxlIHBhaWVtZW50IGF1IFRQRSwKICogICAgICAgICAgICAg
ICAgICAgICBhdHRlbmQgbGEgcsOpcG9uc2UsIHJlbnZvaWUgeyBzdWNjZXNzLCAu
Li4gfQogKgogKiBDT1JTIGVzdCBvdXZlcnQgOiBsYSBwYWdlIGRlIGNhaXNzZSAo
aMOpYmVyZ8OpZSBlbiBodHRwczovLy4uLikgYXBwZWxsZQogKiBjZSBwb250IGVu
IGh0dHA6Ly9pcC1sb2NhbGUgLSBjJ2VzdCB1biBjcm9zcy1vcmlnaW4gYXNzdW3D
qSwgbGltaXTDqSBhdQogKiByw6lzZWF1IGxvY2FsLiBBdWN1bmUgZG9ubsOpZSBz
ZW5zaWJsZSBuZSB0cmFuc2l0ZSBpY2kgKGp1c3RlIHVuIG1vbnRhbnQpLgogKi8K
Cid1c2Ugc3RyaWN0JzsKCmNvbnN0IGh0dHAgPSByZXF1aXJlKCdodHRwJyk7CmNv
bnN0IG5ldCA9IHJlcXVpcmUoJ25ldCcpOwoKLyogLS0tLS0tLS0tLSBMZWN0dXJl
IGRlcyBhcmd1bWVudHMgLS0tLS0tLS0tLSAqLwoKZnVuY3Rpb24gcGFyc2VBcmdz
KGFyZ3YpIHsKICBjb25zdCBvcHRzID0geyB0cGU6IG51bGwsIHBvcnQ6IDg4ODgs
IGxpc3RlbjogNzc4OCwgcG9zOiAnMicsIHByaW50ZXI6ICcnLCBzZXJ2ZXI6IG51
bGwsIHNhbG9uOiBudWxsLCBrZXk6IG51bGwgfTsKICBmb3IgKGxldCBpID0gMDsg
aSA8IGFyZ3YubGVuZ3RoOyBpKyspIHsKICAgIGNvbnN0IGEgPSBhcmd2W2ldOwog
ICAgY29uc3QgbmV4dCA9ICgpID0+IGFyZ3ZbKytpXTsKICAgIGlmIChhID09PSAn
LS10cGUnKSBvcHRzLnRwZSA9IG5leHQoKTsKICAgIGVsc2UgaWYgKGEgPT09ICct
LXBvcnQnKSBvcHRzLnBvcnQgPSBwYXJzZUludChuZXh0KCksIDEwKTsKICAgIGVs
c2UgaWYgKGEgPT09ICctLWxpc3RlbicpIG9wdHMubGlzdGVuID0gcGFyc2VJbnQo
bmV4dCgpLCAxMCk7CiAgICBlbHNlIGlmIChhID09PSAnLS1wb3MnKSBvcHRzLnBv
cyA9IFN0cmluZyhuZXh0KCkpLnNsaWNlKDAsIDEpOwogICAgZWxzZSBpZiAoYSA9
PT0gJy0tcHJpbnRlcicpIG9wdHMucHJpbnRlciA9IFN0cmluZyhuZXh0KCkpOwog
ICAgZWxzZSBpZiAoYSA9PT0gJy0tc2VydmVyJykgb3B0cy5zZXJ2ZXIgPSBTdHJp
bmcobmV4dCgpKTsKICAgIGVsc2UgaWYgKGEgPT09ICctLXNhbG9uJykgb3B0cy5z
YWxvbiA9IFN0cmluZyhuZXh0KCkpOwogICAgZWxzZSBpZiAoYSA9PT0gJy0ta2V5
Jykgb3B0cy5rZXkgPSBTdHJpbmcobmV4dCgpKTsKICAgIGVsc2UgaWYgKGEgPT09
ICctLWhlbHAnIHx8IGEgPT09ICctaCcpIHsgcHJpbnRIZWxwKCk7IHByb2Nlc3Mu
ZXhpdCgwKTsgfQogIH0KICBpZiAoIW9wdHMudHBlICYmICFvcHRzLnNlcnZlcikg
ewogICAgY29uc29sZS5lcnJvcigiWyFdIERvbm5leiBhdSBtb2lucyAtLXRwZSA8
aXAgZHUgVFBFPiBvdSAtLXNlcnZlciA8dXJsIGRlIGwnYXBwPi4gRXhlbXBsZXMg
OiIpOwogICAgY29uc29sZS5lcnJvcignICAgICAgbm9kZSB0cGUtYnJpZGdlLmpz
IC0tdHBlIDE5Mi4xNjguMS4xMjUgLS1wb3MgMicpOwogICAgY29uc29sZS5lcnJv
cignICAgICAgbm9kZSB0cGUtYnJpZGdlLmpzIC0tc2VydmVyIGh0dHBzOi8vbW9u
LWFwcC5jb20gLS1zYWxvbiBtb24tc2Fsb24gLS1rZXkgQ0xFIC0tcHJpbnRlciBF
UFNPTicpOwogICAgcHJvY2Vzcy5leGl0KDEpOwogIH0KICByZXR1cm4gb3B0czsK
fQoKZnVuY3Rpb24gcHJpbnRIZWxwKCkgewogIGNvbnNvbGUubG9nKGAKUG9udCBs
b2NhbCBjYWlzc2UgPC0+IFRQRSArIGltcHJlc3Npb24gc2lsZW5jaWV1c2UKCkRF
VVggTU9ERVMgKGN1bXVsYWJsZXMpIDoKCjEuIFNFUlZFVVIgKHJlY29tbWFuZGUg
cG91ciBsJ2ltcHJlc3Npb24pIC0gbGUgcG9udCBpbnRlcnJvZ2UgbHVpLW1lbWUK
ICAgbCdhcHAgZW4gSFRUUFMgZXQgaW1wcmltZSBsZXMgdGlja2V0cyBkZXBvc8Op
cyBwYXIgbGEgY2Fpc3NlIDoKCiAgIG5vZGUgdHBlLWJyaWRnZS5qcyAtLXNlcnZl
ciBodHRwczovL21vbi1hcHAuY29tIC0tc2Fsb24gbW9uLXNhbG9uIC0ta2V5IENM
RQoKICAgICAtLXNlcnZlciA8dXJsPiAgIFVSTCBkZSBsJ2FwcCAoY2VsbGUgZHUg
bmF2aWdhdGV1ciwgc2FucyAvY2Fpc3NlKQogICAgIC0tc2Fsb24gPHNsdWc+ICAg
SWRlbnRpZmlhbnQgZHUgc2Fsb24gKGNlbHVpIGRlIGwnVVJMID9zYWxvbj0uLi4p
CiAgICAgLS1rZXkgPGNsZT4gICAgICBDbGUgZHUgcG9udCAoRGFzaGJvYXJkID4g
UmVnbGFnZXMgPiBUZXJtaW5hbCBkZSBwYWllbWVudCkKICAgICAtLXByaW50ZXIg
PG5vbT4gIEltcHJpbWFudGUgQ1VQUyAoZGVmYXV0IDogaW1wcmltYW50ZSBwYXIg
ZGVmYXV0KQoKMi4gU0VSVkVVUiBIVFRQIExPQ0FMIChwYWllbWVudCBUUEUpIC0g
bGEgY2Fpc3NlIG91IGwnYXBwIHBldXZlbnQgbHVpCiAgIGRlbGVndWVyIGwnZW52
b2kgQ29uY2VydCBhdSBUUEUgc3VyIGxlIHJlc2VhdSBsb2NhbCA6CgogICBub2Rl
IHRwZS1icmlkZ2UuanMgLS10cGUgMTkyLjE2OC4xLjEyNSBbLS1wb3J0IDg4ODhd
IFstLWxpc3RlbiA3Nzg4XSBbLS1wb3MgMl0KCiAgICAgLS10cGUgPGlwPiAgICAg
ICAgIElQIGR1IHRlcm1pbmFsICh2b2lyIHRpY2tldCBkZSBjb25maWcpCiAgICAg
LS1wb3J0IDxuPiAgICAgICAgIFBvcnQgQ29uY2VydCBkdSBUUEUgKGRlZmF1dCA6
IDg4ODgpCiAgICAgLS1saXN0ZW4gPG4+ICAgICAgIFBvcnQgSFRUUCBkZSBjZSBw
b250IChkZWZhdXQgOiA3Nzg4KQogICAgIC0tcG9zIDxuPiAgICAgICAgICBOdW1l
cm8gZGUgY2Fpc3NlIChkZWZhdXQgOiAyKQpgKTsKfQoKLyogLS0tLS0tLS0tLSBO
ZXB0aW5nIExvY2FsIEFQSSAoQ29uY2VydCB2MyBJUCAvIFRMVikgLS0tLS0tLS0t
LSAqLwoKLyoqCiAqIEZvcm1hdCByw6llbGxlbWVudCB2YWxpZMOpIHN1ciBsZSB0
ZXJtaW5hbCBOZXB0aW5nIGR1IHNhbG9uIDoKICogVENQIHBvcnQgODg4OCwgY2hh
bXBzIFRMViBBU0NJSSBDWi9DSi9DQS9DQi9DRC9DRSwgZmluIGRlIHJlcXXDqnRl
IENSTEYuCiAqIENKIGVzdCB1biBpZGVudGlmaWFudCBsb2dpcXVlIGRlIGNhaXNz
ZSBzdXIgMTIgY2FyYWN0w6hyZXMgOyBvbiBsZSBkw6lyaXZlCiAqIGR1IG51bcOp
cm8gZGUgY2Fpc3NlIGFmaW4gcXUnaWwgc29pdCBzdGFibGUgZXQgdW5pcXVlIHBh
ciBwb3N0ZS4KICovCmZ1bmN0aW9uIG5lcHRpbmdUbHYodGFnLCB2YWx1ZSkgewog
IGNvbnN0IHYgPSBTdHJpbmcodmFsdWUpOwogIHJldHVybiB0YWcgKyBTdHJpbmco
di5sZW5ndGgpLnBhZFN0YXJ0KDMsICcwJykgKyB2Owp9CgpmdW5jdGlvbiBidWls
ZENvbmNlcnRGcmFtZShwb3NOdW1iZXIsIGFtb3VudENlbnRzLCB0cmFuc2FjdGlv
blR5cGUpIHsKICBjb25zdCBwb3MgPSBTdHJpbmcocG9zTnVtYmVyKS5yZXBsYWNl
KC9cRC9nLCAnJykgfHwgJzInOwogIGNvbnN0IHBvczIgPSBwb3MucGFkU3RhcnQo
MiwgJzAnKS5zbGljZSgtMik7CiAgY29uc3QgY2FzaFJlZ2lzdGVySWQgPSBwb3Mu
cGFkU3RhcnQoMTIsICcwJykuc2xpY2UoLTEyKTsKCiAgcmV0dXJuIEJ1ZmZlci5m
cm9tKAogICAgbmVwdGluZ1RsdignQ1onLCAnMDMyMCcpICsKICAgIG5lcHRpbmdU
bHYoJ0NKJywgY2FzaFJlZ2lzdGVySWQpICsKICAgIG5lcHRpbmdUbHYoJ0NBJywg
cG9zMikgKwogICAgbmVwdGluZ1RsdignQ0InLCBTdHJpbmcoYW1vdW50Q2VudHMp
KSArCiAgICBuZXB0aW5nVGx2KCdDRCcsIHRyYW5zYWN0aW9uVHlwZSA9PT0gJ2Ny
ZWRpdCcgPyAnMScgOiAnMCcpICsKICAgIG5lcHRpbmdUbHYoJ0NFJywgJzk3OCcp
ICsKICAgICdcclxuJywKICAgICdhc2NpaScKICApOwp9CgpmdW5jdGlvbiBwYXJz
ZU5lcHRpbmdUbHYodGV4dCkgewogIGNvbnN0IGZpZWxkcyA9IHt9OwogIGNvbnN0
IGNsZWFuID0gU3RyaW5nKHRleHQpLnJlcGxhY2UoL1tcclxuXS9nLCAnJyk7CiAg
bGV0IGkgPSAwOwoKICB3aGlsZSAoaSArIDUgPD0gY2xlYW4ubGVuZ3RoKSB7CiAg
ICBjb25zdCB0YWcgPSBjbGVhbi5zbGljZShpLCBpICsgMik7CiAgICBjb25zdCBs
ZW5UZXh0ID0gY2xlYW4uc2xpY2UoaSArIDIsIGkgKyA1KTsKICAgIGlmICghL15b
QS1aMC05XXsyfSQvLnRlc3QodGFnKSB8fCAhL15cZHszfSQvLnRlc3QobGVuVGV4
dCkpIHsKICAgICAgaSArPSAxOwogICAgICBjb250aW51ZTsKICAgIH0KICAgIGNv
bnN0IGxlbiA9IE51bWJlcihsZW5UZXh0KTsKICAgIGNvbnN0IHZhbHVlU3RhcnQg
PSBpICsgNTsKICAgIGNvbnN0IHZhbHVlRW5kID0gdmFsdWVTdGFydCArIGxlbjsK
ICAgIGlmICh2YWx1ZUVuZCA+IGNsZWFuLmxlbmd0aCkgYnJlYWs7CiAgICBmaWVs
ZHNbdGFnXSA9IGNsZWFuLnNsaWNlKHZhbHVlU3RhcnQsIHZhbHVlRW5kKTsKICAg
IGkgPSB2YWx1ZUVuZDsKICB9CiAgcmV0dXJuIGZpZWxkczsKfQoKZnVuY3Rpb24g
aW50ZXJwcmV0UmVzcG9uc2UoZnJhbWUpIHsKICBjb25zdCBmaWVsZHMgPSBwYXJz
ZU5lcHRpbmdUbHYoZnJhbWUpOwogIGlmICghZmllbGRzLkFFKSB0aHJvdyBuZXcg
RXJyb3IoJ1LDqXBvbnNlIE5lcHRpbmcgaW5jb21wbMOodGUgKGNoYW1wIEFFIGFi
c2VudCknKTsKCiAgY29uc3Qgc3VjY2VzcyA9IGZpZWxkcy5BRSA9PT0gJzEwJzsK
ICByZXR1cm4gewogICAgc3VjY2VzcywKICAgIHJlc3VsdENvZGU6IGZpZWxkcy5B
RSwKICAgIGZhaWx1cmVDb2RlOiBzdWNjZXNzID8gbnVsbCA6IChmaWVsZHMuQUYg
fHwgZmllbGRzLkFFKSwKICAgIGZhaWx1cmVSZWFzb246IHN1Y2Nlc3MgPyBudWxs
IDogKCdQYWllbWVudCByZWZ1c8OpL2FubnVsw6kgKEFFPScgKyBmaWVsZHMuQUUg
KyAoZmllbGRzLkFGID8gJywgQUY9JyArIGZpZWxkcy5BRiA6ICcnKSArICcpJyks
CiAgICBhdXRoTnVtYmVyOiBmaWVsZHMuQUMgfHwgbnVsbCwKICAgIGFtb3VudENl
bnRzOiBmaWVsZHMuQ0IgPyBOdW1iZXIoZmllbGRzLkNCKSA6IG51bGwsCiAgICBj
dXJyZW5jeTogZmllbGRzLkNFIHx8IG51bGwKICB9Owp9CgovKioKICogRW52b2ll
IHVuZSBkZW1hbmRlIE5lcHRpbmcgYXUgVFBFIGV0IGF0dGVuZCBsZSByw6lzdWx0
YXQgZGUgdHJhbnNhY3Rpb24uCiAqIExhIHLDqXBvbnNlIE5lcHRpbmcgbidlc3Qg
cGFzIG7DqWNlc3NhaXJlbWVudCB0ZXJtaW7DqWUgcGFyIENSL0xGIDogb24KICog
Y29uc2lkw6hyZSBsYSByw6lwb25zZSBleHBsb2l0YWJsZSBkw6hzIHF1ZSBsZSBj
aGFtcCBBRSBjb21wbGV0IGVzdCByZcOndS4KICovCmZ1bmN0aW9uIGNvbmNlcnRD
aGFyZ2UoaG9zdCwgcG9ydCwgcG9zLCBhbW91bnRDZW50cywgdGltZW91dE1zKSB7
CiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHsKICAg
IGNvbnN0IGZyYW1lID0gYnVpbGRDb25jZXJ0RnJhbWUocG9zLCBhbW91bnRDZW50
cywgJ2RlYml0Jyk7CiAgICBjb25zdCBzb2NrZXQgPSBuZXQuY3JlYXRlQ29ubmVj
dGlvbih7IGhvc3QsIHBvcnQgfSk7CiAgICBsZXQgcmVzcG9uc2UgPSAnJzsKICAg
IGxldCBzZXR0bGVkID0gZmFsc2U7CgogICAgY29uc3QgdGltZW91dEhhbmRsZSA9
IHNldFRpbWVvdXQoKCkgPT4gewogICAgICBpZiAoc2V0dGxlZCkgcmV0dXJuOwog
ICAgICBzZXR0bGVkID0gdHJ1ZTsKICAgICAgc29ja2V0LmRlc3Ryb3koKTsKICAg
ICAgcmVqZWN0KG5ldyBFcnJvcigiTGUgVFBFIG4nYSBwYXMgcsOpcG9uZHUgw6Ag
dGVtcHMgKHRlcm1pbmFsIGVuIHZlaWxsZSA/IGhvcnMgbGlnbmUgPykiKSk7CiAg
ICB9LCB0aW1lb3V0TXMpOwoKICAgIGNvbnN0IHNldHRsZSA9IChmbiwgdmFsdWUp
ID0+IHsKICAgICAgaWYgKHNldHRsZWQpIHJldHVybjsKICAgICAgc2V0dGxlZCA9
IHRydWU7CiAgICAgIGNsZWFyVGltZW91dCh0aW1lb3V0SGFuZGxlKTsKICAgICAg
c29ja2V0LmRlc3Ryb3koKTsKICAgICAgZm4odmFsdWUpOwogICAgfTsKCiAgICBj
b25zdCB0cnlJbnRlcnByZXQgPSAoKSA9PiB7CiAgICAgIGNvbnN0IGZpZWxkcyA9
IHBhcnNlTmVwdGluZ1RsdihyZXNwb25zZSk7CiAgICAgIGlmICghZmllbGRzLkFF
KSByZXR1cm4gZmFsc2U7CiAgICAgIHRyeSB7CiAgICAgICAgc2V0dGxlKHJlc29s
dmUsIGludGVycHJldFJlc3BvbnNlKHJlc3BvbnNlKSk7CiAgICAgIH0gY2F0Y2gg
KGVycikgewogICAgICAgIHNldHRsZShyZWplY3QsIGVycik7CiAgICAgIH0KICAg
ICAgcmV0dXJuIHRydWU7CiAgICB9OwoKICAgIHNvY2tldC5vbignY29ubmVjdCcs
ICgpID0+IHsKICAgICAgY29uc29sZS5sb2coYFs+XSBEZW1hbmRlIE5lcHRpbmcg
ZGUgJHsoYW1vdW50Q2VudHMgLyAxMDApLnRvRml4ZWQoMil9IOKCrCBlbnZvecOp
ZSDDoCAke2hvc3R9OiR7cG9ydH0gKGNhaXNzZSAke3Bvc30pYCk7CiAgICAgIHNv
Y2tldC53cml0ZShmcmFtZSk7CiAgICB9KTsKCiAgICBzb2NrZXQub24oJ2RhdGEn
LCAoY2h1bmspID0+IHsKICAgICAgcmVzcG9uc2UgKz0gY2h1bmsudG9TdHJpbmco
J2FzY2lpJyk7CiAgICAgIHRyeUludGVycHJldCgpOwogICAgfSk7CgogICAgc29j
a2V0Lm9uY2UoJ2Nsb3NlJywgKCkgPT4gewogICAgICBpZiAoc2V0dGxlZCkgcmV0
dXJuOwogICAgICBpZiAoIXJlc3BvbnNlKSByZXR1cm4gc2V0dGxlKHJlamVjdCwg
bmV3IEVycm9yKCdDb25uZXhpb24gVFBFIGZlcm3DqWUgc2FucyByw6lwb25zZScp
KTsKICAgICAgdHJ5IHsKICAgICAgICBzZXR0bGUocmVzb2x2ZSwgaW50ZXJwcmV0
UmVzcG9uc2UocmVzcG9uc2UpKTsKICAgICAgfSBjYXRjaCAoZXJyKSB7CiAgICAg
ICAgc2V0dGxlKHJlamVjdCwgZXJyKTsKICAgICAgfQogICAgfSk7CgogICAgc29j
a2V0Lm9uKCdlcnJvcicsIChlcnIpID0+IHNldHRsZShyZWplY3QsIGVycikpOwog
IH0pOwp9CgovKiAtLS0tLS0tLS0tIEltcHJlc3Npb24gc2lsZW5jaWV1c2UgLS0t
LS0tLS0tLSAqLwoKY29uc3QgeyBleGVjRmlsZSB9ID0gcmVxdWlyZSgnY2hpbGRf
cHJvY2VzcycpOwpjb25zdCBmcyA9IHJlcXVpcmUoJ2ZzJyk7CmNvbnN0IG9zID0g
cmVxdWlyZSgnb3MnKTsKY29uc3QgcGF0aCA9IHJlcXVpcmUoJ3BhdGgnKTsKCi8q
KgogKiBJbXByaW1lIGR1IHRleHRlIGJydXQgdmlhIENVUFMgKG1hY09TL0xpbnV4
KSBTQU5TIGF1Y3VuZSBib8OudGUgZGUKICogZGlhbG9ndWUgOiBvbiDDqWNyaXQg
dW4gZmljaGllciB0ZW1wb3JhaXJlIGV0IG9uIGxlIHNvdW1ldCDDoCBgbHBgLgog
KiBEZXV4IG1vZGVzIDoKICogIC0gImVzY3BvcyIgIChkw6lmYXV0KSA6IGwnaW1w
cmltYW50ZSBlc3QgdW5lIHRoZXJtaXF1ZSA1OC84MCBtbSA7CiAqICAgIGxlIHRl
eHRlIGVzdCB0cmFuc2NvZMOpIGVuIENQODUwIChqZXUgZGUgY2FyYWN0w6hyZXMg
RVNDL1BPUwogKiAgICBldXJvcMOpZW4sIGF2ZWMgbGUgc2lnbmUg4oKsKSBldCBw
csOpY8OpZMOpIGRlIGxhIGNvbW1hbmRlIEVTQyB0IDExIHF1aQogKiAgICBzw6ls
ZWN0aW9ubmUgbGEgdGFibGUgQ1A4NTAgZGFucyBsJ2ltcHJpbWFudGUuIGBscCAt
byByYXdgIGVzdAogKiAgICByZXF1aXMgKGZpbGUgInJhdyIgYWN0aXbDqWUgcGFy
IGTDqWZhdXQgc3VyIGxhIHBsdXBhcnQgZGVzIHBpbG90ZXMKICogICAgdGhlcm1p
cXVlcykuCiAqICAtICJ0ZXh0IiA6IGltcHJpbWFudGUgY2xhc3NpcXVlIChBNC4u
LikgLSBscCByZW5kcmEgbGUgdGV4dGUKICogICAgcHJvcHJlbWVudCBhdmVjIHNl
cyBmaWx0cmVzIHN0YW5kYXJkcy4KICogcHJpbnRlciA6IG5vbSBDVVBTIChleC4g
IkVQU09OX1RNLVQyMElJSSIpLiBWaWRlID0gaW1wcmltYW50ZSBwYXIKICogZMOp
ZmF1dCBkdSBzeXN0w6htZS4KICogTGUgcmV0b3VyIGNvbnRpZW50IGwnaWRlbnRp
ZmlhbnQgZGUgam9iIENVUFMgKGV4LiAiRVBTT04tMTIzIikgcG91cgogKiB0cmFj
ZXIgbCdpbXByZXNzaW9uLgogKi8KCi8vIFRhYmxlIENQODUwIChFdXJvcGUgZGUg
bCdPdWVzdCkgOiBqZXUgZGUgY2FyYWN0w6hyZXMgc3RhbmRhcmQgZGVzCi8vIGlt
cHJpbWFudGVzIHRoZXJtaXF1ZXMgRVNDL1BPUy4gTCdVVEYtOCBlbnZvecOpIHRl
bCBxdWVsIHMnaW1wcmltZSBlbgovLyBoacOpcm9nbHlwaGVzICjigqwgLT4gIlLD
qeKAoSIsIMOoIC0+ICLigKEiKSBjYXIgbCdpbXByaW1hbnRlIGF0dGVuZCBkdSBD
UDg1MC4KY29uc3QgVVRGOF9UT19DUDg1MCA9IHsKICAn4oKsJzogJ1x4ODAnLCAn
w6AnOiAnXHg4NScsICfDqCc6ICdceDhBJywgJ8OpJzogJ1x4ODInLCAnw6onOiAn
XHg4OCcsCiAgJ8OrJzogJ1x4ODknLCAnw68nOiAnXHg4QicsICfDric6ICdceDhD
JywgJ8O0JzogJ1x4OTMnLCAnw7YnOiAnXHg5NCcsCiAgJ8O5JzogJ1x4OTcnLCAn
w7snOiAnXHg5NicsICfDvCc6ICdceDgxJywgJ8OnJzogJ1x4ODcnLCAnw4cnOiAn
XHg4MCcsCiAgJ8OAJzogJ1x4QjcnLCAnw4gnOiAnXHhENCcsICfDiSc6ICdceDkw
JywgJ8OKJzogJ1x4RDInLCAnw4snOiAnXHhEMycsCiAgJ8OOJzogJ1x4RDcnLCAn
w48nOiAnXHhEOCcsICfDlCc6ICdceEUyJywgJ8OWJzogJ1x4OTknLCAnw5knOiAn
XHhFQicsCiAgJ8ObJzogJ1x4RUEnLCAnw5wnOiAnXHg5QScsICfCsCc6ICdceEY4
JywgJ8KxJzogJ1x4RjEnLCAnwqMnOiAnXHg5QycsCiAgJ8KnJzogJ1x4QTcnLCAn
w5cnOiAnXHg5RCcsICfDtyc6ICdceEY2JywgJ8KrJzogJ1x4QUUnLCAnwrsnOiAn
XHhBRicsCiAgJ86xJzogJ1x4RTAnLCAnw58nOiAnXHhFMScsICfOkyc6ICdceEUy
JywgJ8+AJzogJ1x4RTMnLCAnzqMnOiAnXHhFNCcsCiAgJ8+DJzogJ1x4RTUnLCAn
wrUnOiAnXHhFNicsICfPhCc6ICdceEU3JywgJ86mJzogJ1x4RTgnLCAnzpgnOiAn
XHhFOScsCiAgJ86pJzogJ1x4RUEnLCAnzrQnOiAnXHhFQicsICfiiJ4nOiAnXHhF
QycsICfPhic6ICdceEVEJywgJ861JzogJ1x4RUUnLAogICfiiKknOiAnXHhFRics
ICfiiaEnOiAnXHhGMCcsICfiiaUnOiAnXHhGMicsICfiiaQnOiAnXHhGMycsICfi
jKAnOiAnXHhGNCcsCiAgJ+KMoSc6ICdceEY1JywgJ+KJiCc6ICdceEY3JywgJ+KI
mic6ICdceEZCJywgJ+KBvyc6ICdceEZDJywgJ8KyJzogJ1x4RkQnCn07CgovKiog
VHJhbnNjb2RlIHVuZSBjaGHDrm5lIFVURi04IHZlcnMgdW5lIGNoYcOubmUgQ1A4
NTAgKG9jdGV0cyAxOjEpLiAqLwpmdW5jdGlvbiB0b0NwODUwKHRleHQpIHsKICBs
ZXQgb3V0ID0gJyc7CiAgZm9yIChjb25zdCBjaCBvZiB0ZXh0KSB7CiAgICBpZiAo
VVRGOF9UT19DUDg1MFtjaF0gIT09IHVuZGVmaW5lZCkgb3V0ICs9IFVURjhfVE9f
Q1A4NTBbY2hdOwogICAgZWxzZSBpZiAoY2guY2hhckNvZGVBdCgwKSA8IDEyOCkg
b3V0ICs9IGNoOyAgIC8vIEFTQ0lJIDogaWRlbnRpcXVlCiAgICBlbHNlIG91dCAr
PSAnPyc7ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC8vIGNhcmFjdMOo
cmUgaG9ycyBDUDg1MAogIH0KICByZXR1cm4gb3V0Owp9CgpmdW5jdGlvbiBwcmlu
dFRpY2tldCh0ZXh0LCBwcmludGVyLCBtb2RlKSB7CiAgcmV0dXJuIG5ldyBQcm9t
aXNlKChyZXNvbHZlLCByZWplY3QpID0+IHsKICAgIGxldCBjb250ZW50LCB1c2VS
YXc7CiAgICBpZiAobW9kZSA9PT0gJ2RyYXdlcicpIHsKICAgICAgLy8gQ29tbWFu
ZGUgRVNDL1BPUyBicnV0ZSAob3V2ZXJ0dXJlIGRlIHRpcm9pcikgOiBsZXMgb2N0
ZXRzIGR1CiAgICAgIC8vIHRleHRlIHNvbnQgZMOpasOgIGxhIGNvbW1hbmRlIGNv
bXBsw6h0ZSAoRVNDIHAuLi4pIC0gYXVjdW4KICAgICAgLy8gdHJhbnNjb2RhZ2Us
IGF1Y3VuZSBkw6ljb3VwZSwgcmllbiDDoCBham91dGVyLiBFbnZvaSByYXcgb2Js
aWdhdG9pcmUuCiAgICAgIGNvbnRlbnQgPSBCdWZmZXIuZnJvbSh0ZXh0LCAnYmlu
YXJ5Jyk7CiAgICAgIHVzZVJhdyA9IHRydWU7CiAgICB9IGVsc2UgaWYgKG1vZGUg
PT09ICdlc2Nwb3MnKSB7CiAgICAgIC8vIFRyYW5zY29kYWdlIENQODUwICsgc8Op
bGVjdGlvbiBkZSBsYSB0YWJsZSBkZSBjYXJhY3TDqHJlcyBFU0MgdCAxMQogICAg
ICAvLyAoQ1A4NTApIGVuIHTDqnRlIGRlIGZsdXgsIHB1aXMgZMOpY291cGUgYXV0
b21hdGlxdWUgKEdTIFYgNjYgMCkgZW4gcGllZC4KICAgICAgY29udGVudCA9IEJ1
ZmZlci5jb25jYXQoWwogICAgICAgIEJ1ZmZlci5mcm9tKCdceDFCXHg0MCcsICdh
c2NpaScpLCAgICAgICAgICAgICAgICAgLy8gRVNDIEAgOiByZXNldAogICAgICAg
IEJ1ZmZlci5mcm9tKCdceDFCXHg3NFx4MTEnLCAnYXNjaWknKSwgICAgICAgICAg
ICAgLy8gRVNDIHQgMTEgLT4gdGFibGUgQ1A4NTAKICAgICAgICBCdWZmZXIuZnJv
bSh0b0NwODUwKHRleHQpLCAnYmluYXJ5JyksCiAgICAgICAgQnVmZmVyLmZyb20o
J1xuXG5cbicsICdhc2NpaScpLAogICAgICAgIEJ1ZmZlci5mcm9tKCdceDFEXHg1
Nlx4NDJceDAwJywgJ2FzY2lpJykgICAgICAgICAgLy8gR1MgViA2NiAwIDogZMOp
Y291cGUKICAgICAgXSk7CiAgICAgIHVzZVJhdyA9IHRydWU7CiAgICB9IGVsc2Ug
ewogICAgICBjb250ZW50ID0gQnVmZmVyLmZyb20odGV4dCwgJ3V0ZjgnKTsKICAg
ICAgdXNlUmF3ID0gZmFsc2U7CiAgICB9CgogICAgY29uc3QgdG1wRmlsZSA9IHBh
dGguam9pbihvcy50bXBkaXIoKSwgJ3RpY2tldC0nICsgRGF0ZS5ub3coKSArICcu
YmluJyk7CiAgICBmcy53cml0ZUZpbGUodG1wRmlsZSwgY29udGVudCwgKGVycikg
PT4gewogICAgICBpZiAoZXJyKSByZXR1cm4gcmVqZWN0KG5ldyBFcnJvcignw4lj
cml0dXJlIGR1IHRpY2tldCBpbXBvc3NpYmxlIDogJyArIGVyci5tZXNzYWdlKSk7
CgogICAgICBpZiAocHJvY2Vzcy5wbGF0Zm9ybSA9PT0gJ3dpbjMyJykgewogICAg
ICAgIHJldHVybiBwcmludFRpY2tldFdpbmRvd3ModG1wRmlsZSwgcHJpbnRlciwg
dXNlUmF3LCByZXNvbHZlLCByZWplY3QpOwogICAgICB9CgogICAgICBjb25zdCBh
cmdzID0gW107CiAgICAgIGlmIChwcmludGVyKSBhcmdzLnB1c2goJy1kJywgcHJp
bnRlcik7CiAgICAgIGlmICh1c2VSYXcpIGFyZ3MucHVzaCgnLW8nLCAncmF3Jyk7
CiAgICAgIGFyZ3MucHVzaCgnLXQnLCBtb2RlID09PSAnZHJhd2VyJyA/ICdPdXZl
cnR1cmUtdGlyb2lyJyA6ICdUaWNrZXQtY2Fpc3NlJyk7CiAgICAgIGFyZ3MucHVz
aCh0bXBGaWxlKTsKCiAgICAgIGV4ZWNGaWxlKCdscCcsIGFyZ3MsIHsgdGltZW91
dDogMTUwMDAgfSwgKGVycjIsIHN0ZG91dCwgc3RkZXJyKSA9PiB7CiAgICAgICAg
Ly8gTGUgZmljaGllciB0ZW1wb3JhaXJlIGVzdCBzb3VtaXMgOiBvbiBsZSBzdXBw
cmltZSBxdW9pIHF1J2lsIGFycml2ZQogICAgICAgIGZzLnVubGluayh0bXBGaWxl
LCAoKSA9PiB7fSk7CiAgICAgICAgaWYgKGVycjIpIHsKICAgICAgICAgIGNvbnN0
IG1zZyA9IChzdGRlcnIgfHwgZXJyMi5tZXNzYWdlIHx8ICcnKS50cmltKCk7CiAg
ICAgICAgICByZWplY3QobmV3IEVycm9yKCdJbXByZXNzaW9uIHJlZnVzw6llIHBh
ciBsZSBzeXN0w6htZSA6ICcgKyBtc2cpKTsKICAgICAgICB9IGVsc2UgewogICAg
ICAgICAgcmVzb2x2ZSh7IGpvYklkOiAoc3Rkb3V0IHx8ICcnKS50cmltKCkgfSk7
CiAgICAgICAgfQogICAgICB9KTsKICAgIH0pOwogIH0pOwp9CgovKioKICogSW1w
cmVzc2lvbiBzaWxlbmNpZXVzZSBzdXIgV2luZG93cyA6IENVUFMvbHAgbidleGlz
dGUgcGFzLCBkb25jIHBhcwogKiBkJ8OpcXVpdmFsZW50IGRpcmVjdCDDoCAibHAg
LW8gcmF3Ii4gTGEgbcOpdGhvZGUgZmlhYmxlIGV0IHNhbnMgYXVjdW5lCiAqIGTD
qXBlbmRhbmNlIHBvdXIgZW52b3llciBkZXMgb2N0ZXRzIGJydXRzIChFU0MvUE9T
KSDDoCB1bmUgaW1wcmltYW50ZQogKiBXaW5kb3dzLCBzYW5zIGphbWFpcyBvdXZy
aXIgZGUgYm/DrnRlIGRlIGRpYWxvZ3VlLCBlc3QgZGUgUEFSVEFHRVIKICogbCdp
bXByaW1hbnRlICh1bmUgc2V1bGUgZm9pcywgdm9pciB3aW5kb3dzL1JFQURNRS5t
ZCkgcHVpcyBkZSBjb3BpZXIKICogbGUgZmljaGllciBkaXJlY3RlbWVudCB2ZXJz
IGNlIHBhcnRhZ2UgOiBgY29weSAvYiBmaWNoaWVyIFxcbG9jYWxob3N0XFBhcnRh
Z2VgCiAqIGVudm9pZSBsZXMgb2N0ZXRzIHRlbHMgcXVlbHMgYXUgc3BvdWxldXIs
IHNhbnMgcGFzc2FnZSBwYXIgbGUgcGlsb3RlCiAqIHF1aSByZWZvcm1hdGVyYWl0
IGxlIHRleHRlIChjZSBxdWUgZmFpdCBqdXN0ZW1lbnQgYC1vIHJhd2Agc291cyBD
VVBTKS4KICogYHByaW50ZXJgIGRvaXQgw6p0cmUgbGUgTk9NIERFIFBBUlRBR0Ug
KHBhcyBsZSBub20gZCdpbXByaW1hbnRlIFdpbmRvd3MKICogcydpbHMgZGlmZsOo
cmVudCkgLSDDoCBkw6lmYXV0LCBvbiB1dGlsaXNlIGxlIG5vbSBkJ2ltcHJpbWFu
dGUgcGFyIGTDqWZhdXQKICogZHUgc3lzdMOobWUgY29tbWUgcGFydGFnZSAoZm9u
Y3Rpb25uZSBzaSBzb24gcGFydGFnZSBwb3J0ZSBsZSBtw6ptZSBub20pLgogKi8K
ZnVuY3Rpb24gcHJpbnRUaWNrZXRXaW5kb3dzKHRtcEZpbGUsIHByaW50ZXIsIHVz
ZVJhdywgcmVzb2x2ZSwgcmVqZWN0KSB7CiAgY29uc3QgZmluaXNoID0gKGVyciwg
am9iTGFiZWwpID0+IHsKICAgIGZzLnVubGluayh0bXBGaWxlLCAoKSA9PiB7fSk7
CiAgICBpZiAoZXJyKSByZWplY3QoZXJyKTsKICAgIGVsc2UgcmVzb2x2ZSh7IGpv
YklkOiBqb2JMYWJlbCB9KTsKICB9OwoKICBjb25zdCBzZW5kVG9TaGFyZSA9IChz
aGFyZU5hbWUpID0+IHsKICAgIGNvbnN0IHRhcmdldCA9ICdcXFxcbG9jYWxob3N0
XFwnICsgc2hhcmVOYW1lOwogICAgZXhlY0ZpbGUoJ2NtZC5leGUnLCBbJy9jJywg
J2NvcHknLCAnL2InLCB0bXBGaWxlLCB0YXJnZXRdLCB7IHRpbWVvdXQ6IDE1MDAw
IH0sIChlcnIsIHN0ZG91dCwgc3RkZXJyKSA9PiB7CiAgICAgIGlmIChlcnIpIHsK
ICAgICAgICBmaW5pc2gobmV3IEVycm9yKAogICAgICAgICAgJ0ltcHJlc3Npb24g
cmVmdXPDqWUgcGFyIFdpbmRvd3MgKHBhcnRhZ2UgIicgKyBzaGFyZU5hbWUgKyAn
IiBpbnRyb3V2YWJsZSBvdSBub24gcGFydGFnw6kpIDogJyArCiAgICAgICAgICAo
c3RkZXJyIHx8IGVyci5tZXNzYWdlIHx8ICcnKS50cmltKCkgKwogICAgICAgICAg
JyDigJQgbFwnaW1wcmltYW50ZSBkb2l0IMOqdHJlIHBhcnRhZ8OpZSAodm9pciB3
aW5kb3dzL1JFQURNRS5tZCwgc2VjdGlvbiBJbXByZXNzaW9uKS4nCiAgICAgICAg
KSk7CiAgICAgIH0gZWxzZSB7CiAgICAgICAgZmluaXNoKG51bGwsICdjb3B5IC0+
IFxcXFxsb2NhbGhvc3RcXCcgKyBzaGFyZU5hbWUpOwogICAgICB9CiAgICB9KTsK
ICB9OwoKICBpZiAocHJpbnRlcikgcmV0dXJuIHNlbmRUb1NoYXJlKHByaW50ZXIp
OwoKICAvLyBQYXMgZGUgbm9tIGZvdXJuaSA6IG9uIHJldHJvdXZlIGwnaW1wcmlt
YW50ZSBwYXIgZMOpZmF1dCBkZSBXaW5kb3dzCiAgLy8gdmlhIFBvd2VyU2hlbGws
IGV0IG9uIHRlbnRlIHNvbiBwcm9wcmUgbm9tIGNvbW1lIG5vbSBkZSBwYXJ0YWdl
CiAgLy8gKGNhcyBsZSBwbHVzIGNvdXJhbnQgc2kgbCd1dGlsaXNhdGV1ciBhIHN1
aXZpIGxlIFJFQURNRSkuCiAgZXhlY0ZpbGUoJ3Bvd2Vyc2hlbGwuZXhlJywgWwog
ICAgJy1Ob1Byb2ZpbGUnLCAnLUNvbW1hbmQnLAogICAgIihHZXQtQ2ltSW5zdGFu
Y2UgLUNsYXNzTmFtZSBXaW4zMl9QcmludGVyIHwgV2hlcmUtT2JqZWN0IHsgJF8u
RGVmYXVsdCAtZXEgJHRydWUgfSkuTmFtZSIKICBdLCB7IHRpbWVvdXQ6IDgwMDAg
fSwgKGVyciwgc3Rkb3V0KSA9PiB7CiAgICBjb25zdCBuYW1lID0gKHN0ZG91dCB8
fCAnJykudHJpbSgpOwogICAgaWYgKGVyciB8fCAhbmFtZSkgewogICAgICByZXR1
cm4gZmluaXNoKG5ldyBFcnJvcigKICAgICAgICAnQXVjdW5lIGltcHJpbWFudGUg
cGFyIGTDqWZhdXQgZMOpdGVjdMOpZSBzdXIgV2luZG93cyBldCBhdWN1biAtLXBy
aW50ZXIgZm91cm5pLiAnICsKICAgICAgICAnUHLDqWNpc2V6IGxlIG5vbSBkZSBw
YXJ0YWdlIGRlIGxcJ2ltcHJpbWFudGUgKHdpbmRvd3MvUkVBRE1FLm1kKS4nCiAg
ICAgICkpOwogICAgfQogICAgc2VuZFRvU2hhcmUobmFtZSk7CiAgfSk7Cn0KCi8q
KgogKiBMaXN0ZSBsZXMgaW1wcmltYW50ZXMgY29ubnVlcyBkdSBzeXN0w6htZSwg
cG91ciBhZmZpY2hhZ2UgaW5mb3JtYXRpZgogKiBhdSBkZW1hcnJhZ2UgKGphbWFp
cyB1dGlsaXNlIHBvdXIgaW1wcmltZXIpIC0gbHBzdGF0IHNvdXMgbWFjT1MvCiAq
IExpbnV4LCBQb3dlclNoZWxsIEdldC1QcmludGVyIHNvdXMgV2luZG93cyAobHBz
dGF0IG4nZXhpc3RlIHBhcykuCiAqLwpmdW5jdGlvbiBsaXN0UHJpbnRlcnMoY2Fs
bGJhY2spIHsKICBpZiAocHJvY2Vzcy5wbGF0Zm9ybSA9PT0gJ3dpbjMyJykgewog
ICAgZXhlY0ZpbGUoJ3Bvd2Vyc2hlbGwuZXhlJywgWwogICAgICAnLU5vUHJvZmls
ZScsICctQ29tbWFuZCcsICdHZXQtQ2ltSW5zdGFuY2UgLUNsYXNzTmFtZSBXaW4z
Ml9QcmludGVyIHwgU2VsZWN0LU9iamVjdCAtRXhwYW5kUHJvcGVydHkgTmFtZScK
ICAgIF0sIChlcnIsIHN0ZG91dCkgPT4gY2FsbGJhY2soZXJyLCBzdGRvdXQpKTsK
ICB9IGVsc2UgewogICAgZXhlY0ZpbGUoJ2xwc3RhdCcsIFsnLWEnXSwgKGVyciwg
c3Rkb3V0KSA9PiBjYWxsYmFjayhlcnIsIHN0ZG91dCkpOwogIH0KfQoKLyogLS0t
LS0tLS0tLSBTZXJ2ZXVyIEhUVFAgLS0tLS0tLS0tLSAqLwoKY29uc3QgQ09SU19I
RUFERVJTID0gewogICdBY2Nlc3MtQ29udHJvbC1BbGxvdy1PcmlnaW4nOiAnKics
CiAgJ0FjY2Vzcy1Db250cm9sLUFsbG93LU1ldGhvZHMnOiAnR0VULCBQT1NULCBP
UFRJT05TJywKICAnQWNjZXNzLUNvbnRyb2wtQWxsb3ctSGVhZGVycyc6ICdDb250
ZW50LVR5cGUnLAogIC8vIENocm9tZSAoUHJpdmF0ZSBOZXR3b3JrIEFjY2Vzcykg
OiB1bmUgcGFnZSBIVFRQUyBxdWkgYXBwZWxsZSB1bgogIC8vIHNlcnZldXIgZHUg
csOpc2VhdSBsb2NhbCBlbnZvaWUgZCdhYm9yZCB1bmUgcmVxdcOqdGUgT1BUSU9O
UyBhdmVjCiAgLy8gIkFjY2Vzcy1Db250cm9sLVJlcXVlc3QtUHJpdmF0ZS1OZXR3
b3JrOiB0cnVlIiAtIHNhbnMgbGEgcsOpcG9uc2UKICAvLyBjaS1kZXNzb3VzLCBs
ZSBuYXZpZ2F0ZXVyIGJsb3F1ZSBzaWxlbmNpZXVzZW1lbnQgbCdhcHBlbC4KICAn
QWNjZXNzLUNvbnRyb2wtQWxsb3ctUHJpdmF0ZS1OZXR3b3JrJzogJ3RydWUnCn07
CgpmdW5jdGlvbiBzZW5kSnNvbihyZXMsIHN0YXR1cywgb2JqKSB7CiAgY29uc3Qg
Ym9keSA9IEpTT04uc3RyaW5naWZ5KG9iaik7CiAgcmVzLndyaXRlSGVhZChzdGF0
dXMsIE9iamVjdC5hc3NpZ24oeyAnQ29udGVudC1UeXBlJzogJ2FwcGxpY2F0aW9u
L2pzb24nIH0sIENPUlNfSEVBREVSUykpOwogIHJlcy5lbmQoYm9keSk7Cn0KCmZ1
bmN0aW9uIG1haW4oKSB7CiAgY29uc3Qgb3B0cyA9IHBhcnNlQXJncyhwcm9jZXNz
LmFyZ3Yuc2xpY2UoMikpOwoKICAvLyBNb2RlIFNFUlZFVVIgOiBsZSBwb250IGlu
dGVycm9nZSBsJ2FwcCBlbiBIVFRQUyBldCBpbXByaW1lIGxlcwogIC8vIHRpY2tl
dHMgZMOpcG9zw6lzIHBhciBsYSBjYWlzc2UuIEF1Y3VuIHBvcnQgbG9jYWwgcmVx
dWlzLgogIGlmIChvcHRzLnNlcnZlcikgewogICAgY29uc29sZS5sb2coJz09PSBQ
b250IGRcJ2ltcHJlc3Npb24gKG1vZGUgc2VydmV1cikgPT09Jyk7CiAgICBjb25z
b2xlLmxvZyhgQXBwICAgICAgICAgICA6ICR7b3B0cy5zZXJ2ZXJ9YCk7CiAgICBj
b25zb2xlLmxvZyhgU2Fsb24gICAgICAgICA6ICR7b3B0cy5zYWxvbn1gKTsKICAg
IGNvbnNvbGUubG9nKGBJbXByaW1hbnRlICAgIDogJHtvcHRzLnByaW50ZXIgfHwg
J2ltcHJpbWFudGUgcGFyIGTDqWZhdXQgZHUgc3lzdMOobWUnfWApOwogICAgbGlz
dFByaW50ZXJzKChlcnIsIHN0ZG91dCkgPT4gewogICAgICBpZiAoZXJyIHx8ICFz
dGRvdXQudHJpbSgpKSBjb25zb2xlLmxvZygnSW1wcmltYW50ZXMgICA6IChhdWN1
bmUgZMOpdGVjdMOpZSknKTsKICAgICAgZWxzZSBjb25zb2xlLmxvZygnSW1wcmlt
YW50ZXMgICA6ICcgKyBzdGRvdXQudHJpbSgpLnNwbGl0KCdcbicpLmpvaW4oJyB8
ICcpKTsKICAgIH0pOwogICAgc3RhcnRTZXJ2ZXJQb2xsaW5nKG9wdHMpOwogICAg
cmV0dXJuOwogIH0KCiAgLy8gTW9kZSBIVFRQIExPQ0FMIChwYWllbWVudCBUUEUp
IC0gaW5jaGFuZ8OpLgogIGNvbnN0IHNlcnZlciA9IGh0dHAuY3JlYXRlU2VydmVy
KChyZXEsIHJlcykgPT4gewogICAgaWYgKHJlcS5tZXRob2QgPT09ICdPUFRJT05T
JykgewogICAgICByZXMud3JpdGVIZWFkKDIwNCwgQ09SU19IRUFERVJTKTsKICAg
ICAgcmV0dXJuIHJlcy5lbmQoKTsKICAgIH0KCiAgICBpZiAocmVxLm1ldGhvZCA9
PT0gJ0dFVCcgJiYgcmVxLnVybC5zcGxpdCgnPycpWzBdID09PSAnL2hlYWx0aCcp
IHsKICAgICAgcmV0dXJuIHNlbmRKc29uKHJlcywgMjAwLCB7IG9rOiB0cnVlLCB0
cGU6IG9wdHMudHBlLCBwb3M6IG9wdHMucG9zIH0pOwogICAgfQoKICAgIC8vIElt
cHJlc3Npb24gc2lsZW5jaWV1c2UgZCd1biB0aWNrZXQgKHRleHRlIGJydXQpLiBM
YSBjYWlzc2UgZ8OpbsOocmUKICAgIC8vIGxlIHRleHRlIGR1IHRpY2tldCBldCBs
ZSBwb3Vzc2UgaWNpIDsgbGUgcG9udCBsZSBzb3VtZXQgw6AgbHAKICAgIC8vIChD
VVBTKSBzYW5zIGF1Y3VuZSBib8OudGUgZGUgZGlhbG9ndWUuCiAgICAvLyBCb2R5
IDogeyB0ZXh0OiAiLi4uIiwgbW9kZTogImVzY3BvcyJ8InRleHQiIChkw6lmYXV0
IGVzY3BvcyksIHByaW50ZXI6ICJOT00iIH0KICAgIGlmIChyZXEubWV0aG9kID09
PSAnUE9TVCcgJiYgcmVxLnVybC5zcGxpdCgnPycpWzBdID09PSAnL3ByaW50Jykg
ewogICAgICBsZXQgYm9keSA9ICcnOwogICAgICByZXEub24oJ2RhdGEnLCAoYykg
PT4geyBib2R5ICs9IGM7IGlmIChib2R5Lmxlbmd0aCA+IDEwMF8wMDApIHJlcS5k
ZXN0cm95KCk7IH0pOwogICAgICByZXEub24oJ2VuZCcsIGFzeW5jICgpID0+IHsK
ICAgICAgICBsZXQgcGF5bG9hZDsKICAgICAgICB0cnkgewogICAgICAgICAgcGF5
bG9hZCA9IEpTT04ucGFyc2UoYm9keSk7CiAgICAgICAgfSBjYXRjaCAoZSkgewog
ICAgICAgICAgcmV0dXJuIHNlbmRKc29uKHJlcywgNDAwLCB7IGVycm9yOiAnUmVx
dcOqdGUgaW52YWxpZGUnIH0pOwogICAgICAgIH0KICAgICAgICBjb25zdCB0ZXh0
ID0gdHlwZW9mIHBheWxvYWQudGV4dCA9PT0gJ3N0cmluZycgPyBwYXlsb2FkLnRl
eHQgOiAnJzsKICAgICAgICBpZiAoIXRleHQudHJpbSgpKSByZXR1cm4gc2VuZEpz
b24ocmVzLCA0MDAsIHsgZXJyb3I6ICdUaWNrZXQgdmlkZScgfSk7CiAgICAgICAg
Y29uc3QgbW9kZSA9IHBheWxvYWQubW9kZSA9PT0gJ3RleHQnID8gJ3RleHQnIDog
J2VzY3Bvcyc7CiAgICAgICAgY29uc3QgcHJpbnRlciA9IHR5cGVvZiBwYXlsb2Fk
LnByaW50ZXIgPT09ICdzdHJpbmcnICYmIHBheWxvYWQucHJpbnRlci50cmltKCkg
PyBwYXlsb2FkLnByaW50ZXIudHJpbSgpIDogb3B0cy5wcmludGVyIHx8ICcnOwoK
ICAgICAgICBjb25zb2xlLmxvZyhgWyR7bmV3IERhdGUoKS50b0xvY2FsZVRpbWVT
dHJpbmcoKX1dIEltcHJlc3Npb24gKCR7bW9kZX0ke3ByaW50ZXIgPyAnLCAnICsg
cHJpbnRlciA6ICcsIGTDqWZhdXQnfSkg4oCUICR7dGV4dC5sZW5ndGh9IGNhcmFj
dMOocmVzYCk7CiAgICAgICAgdHJ5IHsKICAgICAgICAgIGNvbnN0IG91dCA9IGF3
YWl0IHByaW50VGlja2V0KHRleHQsIHByaW50ZXIsIG1vZGUpOwogICAgICAgICAg
Y29uc29sZS5sb2coJ1s8XSBJbXByZXNzaW9uIHNvdW1pc2UgOicsIG91dC5qb2JJ
ZCB8fCAnKGpvYiBDVVBTIHNhbnMgaWQpJyk7CiAgICAgICAgICBzZW5kSnNvbihy
ZXMsIDIwMCwgT2JqZWN0LmFzc2lnbih7IG9rOiB0cnVlIH0sIG91dCkpOwogICAg
ICAgIH0gY2F0Y2ggKGVycikgewogICAgICAgICAgY29uc29sZS5lcnJvcignWyFd
IMOJY2hlYyBpbXByZXNzaW9uIDonLCBlcnIubWVzc2FnZSk7CiAgICAgICAgICBz
ZW5kSnNvbihyZXMsIDUwMiwgeyBlcnJvcjogZXJyLm1lc3NhZ2UgfSk7CiAgICAg
ICAgfQogICAgICB9KTsKICAgICAgcmV0dXJuOwogICAgfQoKICAgIGlmIChyZXEu
bWV0aG9kID09PSAnUE9TVCcgJiYgcmVxLnVybC5zcGxpdCgnPycpWzBdID09PSAn
L2NoYXJnZScpIHsKICAgICAgbGV0IGJvZHkgPSAnJzsKICAgICAgcmVxLm9uKCdk
YXRhJywgKGMpID0+IHsgYm9keSArPSBjOyBpZiAoYm9keS5sZW5ndGggPiAxMF8w
MDApIHJlcS5kZXN0cm95KCk7IH0pOwogICAgICByZXEub24oJ2VuZCcsIGFzeW5j
ICgpID0+IHsKICAgICAgICBsZXQgYW1vdW50Q2VudHM7CiAgICAgICAgdHJ5IHsK
ICAgICAgICAgIGFtb3VudENlbnRzID0gTnVtYmVyKEpTT04ucGFyc2UoYm9keSku
YW1vdW50X2NlbnRzKTsKICAgICAgICB9IGNhdGNoIChlKSB7CiAgICAgICAgICBy
ZXR1cm4gc2VuZEpzb24ocmVzLCA0MDAsIHsgZXJyb3I6ICdSZXF1w6p0ZSBpbnZh
bGlkZScgfSk7CiAgICAgICAgfQogICAgICAgIGlmICghTnVtYmVyLmlzSW50ZWdl
cihhbW91bnRDZW50cykgfHwgYW1vdW50Q2VudHMgPD0gMCkgewogICAgICAgICAg
cmV0dXJuIHNlbmRKc29uKHJlcywgNDAwLCB7IGVycm9yOiAnTW9udGFudCBpbnZh
bGlkZScgfSk7CiAgICAgICAgfQoKICAgICAgICBjb25zb2xlLmxvZyhgWyR7bmV3
IERhdGUoKS50b0xvY2FsZVRpbWVTdHJpbmcoKX1dIFBhaWVtZW50ICR7KGFtb3Vu
dENlbnRzIC8gMTAwKS50b0ZpeGVkKDIpfSDigqwgLT4gVFBFICR7b3B0cy50cGV9
OiR7b3B0cy5wb3J0fWApOwogICAgICAgIHRyeSB7CiAgICAgICAgICBjb25zdCBy
ZXN1bHQgPSBhd2FpdCBjb25jZXJ0Q2hhcmdlKG9wdHMudHBlLCBvcHRzLnBvcnQs
IG9wdHMucG9zLCBhbW91bnRDZW50cywgMTIwMDAwKTsKICAgICAgICAgIGNvbnNv
bGUubG9nKGBbPF0gUsOpc3VsdGF0IDogJHtyZXN1bHQuc3VjY2VzcyA/ICdBQ0NF
UFTDiScgOiAnUkVGVVPDiSAoJyArIChyZXN1bHQuZmFpbHVyZVJlYXNvbiB8fCBy
ZXN1bHQucmVzdWx0Q29kZSkgKyAnKSd9YCk7CiAgICAgICAgICBzZW5kSnNvbihy
ZXMsIDIwMCwgT2JqZWN0LmFzc2lnbih7IG9rOiB0cnVlIH0sIHJlc3VsdCkpOwog
ICAgICAgIH0gY2F0Y2ggKGVycikgewogICAgICAgICAgY29uc29sZS5lcnJvcign
WyFdIMOJY2hlYyA6JywgZXJyLm1lc3NhZ2UpOwogICAgICAgICAgc2VuZEpzb24o
cmVzLCA1MDIsIHsgZXJyb3I6IGVyci5tZXNzYWdlIH0pOwogICAgICAgIH0KICAg
ICAgfSk7CiAgICAgIHJldHVybjsKICAgIH0KCiAgICBzZW5kSnNvbihyZXMsIDQw
NCwgeyBlcnJvcjogJ0VuZHBvaW50IGluY29ubnUnIH0pOwogIH0pOwoKICBzZXJ2
ZXIubGlzdGVuKG9wdHMubGlzdGVuLCAoKSA9PiB7CiAgICBjb25zb2xlLmxvZygn
PT09IFBvbnQgVFBFIENvbmNlcnQgdjMgKyBpbXByZXNzaW9uID09PScpOwogICAg
Y29uc29sZS5sb2coYFRQRSBjaWJsZSAgICAgOiAke29wdHMudHBlID8gb3B0cy50
cGUgKyAnOicgKyBvcHRzLnBvcnQgKyAnIChuwrAgY2Fpc3NlICcgKyBvcHRzLnBv
cyArICcpJyA6ICcoaW1wcmVzc2lvbiBzZXVsZSAtIHBhcyBkZSBUUEUgY29uZmln
dXLDqSknfWApOwogICAgY29uc29sZS5sb2coYEltcHJpbWFudGUgICAgOiAke29w
dHMucHJpbnRlciB8fCAnaW1wcmltYW50ZSBwYXIgZMOpZmF1dCBkdSBzeXN0w6ht
ZSd9YCk7CiAgICBjb25zb2xlLmxvZyhgUG9udCBlbiDDqWNvdXRlOiBodHRwOi8v
MC4wLjAuMDoke29wdHMubGlzdGVufWApOwogICAgY29uc29sZS5sb2coYFNhbnTD
qSAgICAgICAgIDogaHR0cDovL2xvY2FsaG9zdDoke29wdHMubGlzdGVufS9oZWFs
dGhgKTsKICAgIGNvbnNvbGUubG9nKCcnKTsKICAgIGNvbnNvbGUubG9nKCdEYW5z
IGxhIGNhaXNzZSAoRGFzaGJvYXJkID4gUsOpZ2xhZ2VzID4gVGVybWluYWwgZGUg
cGFpZW1lbnQpLCByZW5zZWlnbmV6IDonKTsKICAgIGNvbnNvbGUubG9nKGAgIFBv
bnQgbG9jYWwgOiBodHRwOi8vPGlwLWRlLWNldC1vcmRpbmF0ZXVyPjoke29wdHMu
bGlzdGVufWApOwogICAgY29uc29sZS5sb2coJycpOwogICAgY29uc29sZS5sb2co
J0ltcHJpbWFudGVzIGRpc3BvbmlibGVzIDonKTsKICAgIGxpc3RQcmludGVycygo
ZXJyLCBzdGRvdXQpID0+IHsKICAgICAgaWYgKGVyciB8fCAhc3Rkb3V0LnRyaW0o
KSkgY29uc29sZS5sb2coJyAgKGF1Y3VuZSBpbXByaW1hbnRlIGTDqXRlY3TDqWUp
Jyk7CiAgICAgIGVsc2Ugc3Rkb3V0LnRyaW0oKS5zcGxpdCgnXG4nKS5mb3JFYWNo
KChsKSA9PiBjb25zb2xlLmxvZygnICAnICsgbCkpOwogICAgfSk7CiAgICBjb25z
b2xlLmxvZygnJyk7CiAgICBjb25zb2xlLmxvZygnRW4gYXR0ZW50ZSBkZSBwYWll
bWVudHMgZXQgaW1wcmVzc2lvbnMuLi4gKEN0cmwrQyBwb3VyIGFycsOqdGVyKScp
OwogIH0pOwoKICBzZXJ2ZXIub24oJ2Vycm9yJywgKGVycikgPT4gewogICAgY29u
c29sZS5lcnJvcignWyFdIEVycmV1ciBzZXJ2ZXVyIDonLCBlcnIubWVzc2FnZSk7
CiAgICBwcm9jZXNzLmV4aXQoMSk7CiAgfSk7Cn0KCi8qIC0tLS0tLS0tLS0gTW9k
ZSBTRVJWRVVSIDogcG9sbGluZyBkZSBsJ2FwcCBlbiBIVFRQUyAtLS0tLS0tLS0t
ICovCgpjb25zdCBQT0xMX0lOVEVSVkFMX01TID0gMzAwMDsKCi8qKgogKiBSw6lj
dXDDqHJlIGxlcyB0aWNrZXRzIGVuIGF0dGVudGUgc3VyIGwnYXBwIGV0IGxlcyBp
bXByaW1lLCBwdWlzIGxlcwogKiBkZW1hbmRlcyBkZSBwYWllbWVudCBDQiBldCBs
ZXMgdHJhaXRlLiBMZSBwb250IGVzdCBsZSBDTElFTlQgSFRUUFMgOgogKiBwbHVz
IGF1Y3VuIGFwcGVsIG5hdmlnYXRldXIgLT4gcsOpc2VhdSBsb2NhbCAocXVlIENo
cm9tZSBpbnRlcmRpdCkgLQogKiB0b3V0IHBhc3NlIHBhciBsZSBzZXJ2ZXVyIGVu
IGh0dHBzLCBhdXRvcmlzw6kuCiAqLwphc3luYyBmdW5jdGlvbiBwb2xsT25jZShv
cHRzKSB7CiAgLyogLS0tIDEuIFRpY2tldHMgw6AgaW1wcmltZXIgLS0tICovCiAg
bGV0IGpvYnM7CiAgdHJ5IHsKICAgIGNvbnN0IHJlcyA9IGF3YWl0IGZldGNoKAog
ICAgICBvcHRzLnNlcnZlci5yZXBsYWNlKC9cLyQvLCAnJykgKyAnL2FwaS90cGUv
YnJpZGdlL3BvbGw/c2Fsb249JyArIGVuY29kZVVSSUNvbXBvbmVudChvcHRzLnNh
bG9uKSwKICAgICAgeyBoZWFkZXJzOiB7ICdYLUJyaWRnZS1LZXknOiBvcHRzLmtl
eSwgJ1gtU2Fsb24tU2x1Zyc6IG9wdHMuc2Fsb24gfSB9CiAgICApOwogICAgaWYg
KCFyZXMub2spIHsKICAgICAgY29uc3QgZGV0YWlsID0gYXdhaXQgcmVzLmpzb24o
KS5jYXRjaCgoKSA9PiAoe30pKTsKICAgICAgdGhyb3cgbmV3IEVycm9yKCdIVFRQ
ICcgKyByZXMuc3RhdHVzICsgKGRldGFpbC5lcnJvciA/ICcgLSAnICsgZGV0YWls
LmVycm9yIDogJycpKTsKICAgIH0KICAgIGNvbnN0IGRhdGEgPSBhd2FpdCByZXMu
anNvbigpOwogICAgam9icyA9IGRhdGEuam9icyB8fCBbXTsKICB9IGNhdGNoIChl
cnIpIHsKICAgIGNvbnNvbGUuZXJyb3IoJ1twb2xsXSBzZXJ2ZXVyIGluam9pZ25h
YmxlIDonLCBlcnIubWVzc2FnZSk7CiAgICByZXR1cm47CiAgfQoKICBmb3IgKGNv
bnN0IGpvYiBvZiBqb2JzKSB7CiAgICBjb25zb2xlLmxvZyhgWyR7bmV3IERhdGUo
KS50b0xvY2FsZVRpbWVTdHJpbmcoKX1dIFRpY2tldCAke2pvYi5pZC5zbGljZSgw
LCA4KX0gKCR7am9iLm1vZGV9KSDigJQgaW1wcmVzc2lvbi4uLmApOwogICAgdHJ5
IHsKICAgICAgY29uc3Qgb3V0ID0gYXdhaXQgcHJpbnRUaWNrZXQoam9iLnRleHQs
IG9wdHMucHJpbnRlciwgam9iLm1vZGUpOwogICAgICBjb25zb2xlLmxvZygnWzxd
IEltcHJpbcOpIDonLCBvdXQuam9iSWQgfHwgJyhqb2IgQ1VQUyBzYW5zIGlkKScp
OwogICAgICBhd2FpdCBhY2tKb2Iob3B0cywgam9iLmlkLCB0cnVlLCBudWxsKTsK
ICAgIH0gY2F0Y2ggKGVycikgewogICAgICBjb25zb2xlLmVycm9yKCdbIV0gw4lj
aGVjIGltcHJlc3Npb24gOicsIGVyci5tZXNzYWdlKTsKICAgICAgYXdhaXQgYWNr
Sm9iKG9wdHMsIGpvYi5pZCwgZmFsc2UsIGVyci5tZXNzYWdlKTsKICAgIH0KICB9
CgogIC8qIC0tLSAyLiBEZW1hbmRlcyBkZSBwYWllbWVudCBDQiAoc2kgdW4gVFBF
IGVzdCBjb25maWd1csOpKSAtLS0gKi8KICBpZiAoIW9wdHMudHBlKSByZXR1cm47
CiAgbGV0IGNoYXJnZUpvYnM7CiAgdHJ5IHsKICAgIGNvbnN0IHJlcyA9IGF3YWl0
IGZldGNoKAogICAgICBvcHRzLnNlcnZlci5yZXBsYWNlKC9cLyQvLCAnJykgKyAn
L2FwaS90cGUvYnJpZGdlL2NoYXJnZS1wb2xsP3NhbG9uPScgKyBlbmNvZGVVUklD
b21wb25lbnQob3B0cy5zYWxvbiksCiAgICAgIHsgaGVhZGVyczogeyAnWC1Ccmlk
Z2UtS2V5Jzogb3B0cy5rZXksICdYLVNhbG9uLVNsdWcnOiBvcHRzLnNhbG9uIH0g
fQogICAgKTsKICAgIGlmICghcmVzLm9rKSByZXR1cm47CiAgICBjb25zdCBkYXRh
ID0gYXdhaXQgcmVzLmpzb24oKTsKICAgIGNoYXJnZUpvYnMgPSBkYXRhLmpvYnMg
fHwgW107CiAgfSBjYXRjaCAoZXJyKSB7CiAgICByZXR1cm47IC8vIGTDqWrDoCBs
b2dnw6kgY8O0dMOpIHRpY2tldHMKICB9CgogIGZvciAoY29uc3Qgam9iIG9mIGNo
YXJnZUpvYnMpIHsKICAgIGNvbnNvbGUubG9nKGBbJHtuZXcgRGF0ZSgpLnRvTG9j
YWxlVGltZVN0cmluZygpfV0gUGFpZW1lbnQgQ0IgJHsoam9iLmFtb3VudF9jZW50
cyAvIDEwMCkudG9GaXhlZCgyKX0g4oKsIC0+IFRQRSAke29wdHMudHBlfToke29w
dHMucG9ydH1gKTsKICAgIHRyeSB7CiAgICAgIGNvbnN0IHJlc3VsdCA9IGF3YWl0
IGNvbmNlcnRDaGFyZ2Uob3B0cy50cGUsIG9wdHMucG9ydCwgb3B0cy5wb3MsIGpv
Yi5hbW91bnRfY2VudHMsIDEyMDAwMCk7CiAgICAgIGNvbnNvbGUubG9nKGBbPF0g
UsOpc3VsdGF0IENCIDogJHtyZXN1bHQuc3VjY2VzcyA/ICdBQ0NFUFTDiScgOiAn
UkVGVVPDiSAoJyArIChyZXN1bHQuZmFpbHVyZVJlYXNvbiB8fCByZXN1bHQucmVz
dWx0Q29kZSkgKyAnKSd9YCk7CiAgICAgIGF3YWl0IGFja0NoYXJnZUpvYihvcHRz
LCBqb2IuaWQsIHJlc3VsdCwgbnVsbCk7CiAgICB9IGNhdGNoIChlcnIpIHsKICAg
ICAgY29uc29sZS5lcnJvcignWyFdIMOJY2hlYyBDQiA6JywgZXJyLm1lc3NhZ2Up
OwogICAgICBhd2FpdCBhY2tDaGFyZ2VKb2Iob3B0cywgam9iLmlkLCBudWxsLCBl
cnIubWVzc2FnZSk7CiAgICB9CiAgfQp9CgovKiogUmFwcG9ydGUgbGUgcsOpc3Vs
dGF0IGQndW4gcGFpZW1lbnQgQ0IgYXUgc2VydmV1ci4gKi8KYXN5bmMgZnVuY3Rp
b24gYWNrQ2hhcmdlSm9iKG9wdHMsIGpvYklkLCByZXN1bHQsIGVycm9yKSB7CiAg
dHJ5IHsKICAgIGF3YWl0IGZldGNoKG9wdHMuc2VydmVyLnJlcGxhY2UoL1wvJC8s
ICcnKSArICcvYXBpL3RwZS9icmlkZ2UvY2hhcmdlLWFjaycsIHsKICAgICAgbWV0
aG9kOiAnUE9TVCcsCiAgICAgIGhlYWRlcnM6IHsKICAgICAgICAnWC1CcmlkZ2Ut
S2V5Jzogb3B0cy5rZXksCiAgICAgICAgJ1gtU2Fsb24tU2x1Zyc6IG9wdHMuc2Fs
b24sCiAgICAgICAgJ0NvbnRlbnQtVHlwZSc6ICdhcHBsaWNhdGlvbi9qc29uJwog
ICAgICB9LAogICAgICBib2R5OiBKU09OLnN0cmluZ2lmeSh7IGpvYl9pZDogam9i
SWQsIHJlc3VsdCwgZXJyb3IgfSkKICAgIH0pOwogIH0gY2F0Y2ggKGVycikgewog
ICAgY29uc29sZS5lcnJvcignW2FjayBDQl0gaW1wb3NzaWJsZSA6JywgZXJyLm1l
c3NhZ2UpOwogIH0KfQoKYXN5bmMgZnVuY3Rpb24gYWNrSm9iKG9wdHMsIGpvYklk
LCBvaywgZXJyb3IpIHsKICB0cnkgewogICAgYXdhaXQgZmV0Y2gob3B0cy5zZXJ2
ZXIucmVwbGFjZSgvXC8kLywgJycpICsgJy9hcGkvdHBlL2JyaWRnZS9hY2snLCB7
CiAgICAgIG1ldGhvZDogJ1BPU1QnLAogICAgICBoZWFkZXJzOiB7CiAgICAgICAg
J1gtQnJpZGdlLUtleSc6IG9wdHMua2V5LAogICAgICAgICdYLVNhbG9uLVNsdWcn
OiBvcHRzLnNhbG9uLAogICAgICAgICdDb250ZW50LVR5cGUnOiAnYXBwbGljYXRp
b24vanNvbicKICAgICAgfSwKICAgICAgYm9keTogSlNPTi5zdHJpbmdpZnkoeyBq
b2JfaWQ6IGpvYklkLCBvaywgZXJyb3IgfSkKICAgIH0pOwogIH0gY2F0Y2ggKGVy
cikgewogICAgLy8gUGFzIGdyYXZlIDogbGUgam9iIHJlc3RlcmEgJ3BlbmRpbmcn
IGV0IHNlcmEgcmUtc291bWlzIGF1IHByb2NoYWluCiAgICAvLyBwb2xsIChpbXBy
ZXNzaW9uIGVuIGRvdWJsZSBwb3NzaWJsZSBlbiBjYXMgZGUgY3Jhc2ggZW50cmUg
bGVzIGRldXgKICAgIC8vIGFwcGVscywgc2PDqW5hcmlvIGV4dHLDqm1lbWVudCBy
YXJlIGV0IHByw6lmw6lyYWJsZSDDoCB1biB0aWNrZXQgcGVyZHUpLgogICAgY29u
c29sZS5lcnJvcignW2Fja10gaW1wb3NzaWJsZSA6JywgZXJyLm1lc3NhZ2UpOwog
IH0KfQoKZnVuY3Rpb24gc3RhcnRTZXJ2ZXJQb2xsaW5nKG9wdHMpIHsKICBjb25z
b2xlLmxvZyhgTW9kZSBzZXJ2ZXVyIDogcG9sbGluZyAke29wdHMuc2VydmVyfSAo
c2Fsb24gIiR7b3B0cy5zYWxvbn0iKSB0b3V0ZXMgbGVzICR7UE9MTF9JTlRFUlZB
TF9NUyAvIDEwMDB9IHNgKTsKICBjb25zdCBsb29wID0gYXN5bmMgKCkgPT4gewog
ICAgdHJ5IHsgYXdhaXQgcG9sbE9uY2Uob3B0cyk7IH0gY2F0Y2ggKGVycikgeyBj
b25zb2xlLmVycm9yKCdbcG9sbF0nLCBlcnIubWVzc2FnZSk7IH0KICAgIHNldFRp
bWVvdXQobG9vcCwgUE9MTF9JTlRFUlZBTF9NUyk7CiAgfTsKICBsb29wKCk7Cn0K
Cm1haW4oKTs=
-----END CERTIFICATE-----
:TPE_BRIDGE_CORE_END
:TPE_BRIDGE_WIN_BEGIN
-----BEGIN CERTIFICATE-----
IyEvdXNyL2Jpbi9lbnYgbm9kZQovKioKICogVFBFIEJyaWRnZSDigJQgbGFuY2V1
ciBXaW5kb3dzIGNvbnZpdmlhbC4KICoKICogT2JqZWN0aWYgOiBzdXIgbGUgbWlu
aS1QQyBkdSBzYWxvbiwgbGUgY29pZmZldXIgZG91YmxlLWNsaXF1ZSBzdXIKICog
IlRQRSBCcmlkZ2UiIGV0IG4nYSBSSUVOIGQnYXV0cmUgw6AgZmFpcmUuIENlIHdy
YXBwZXIgOgogKgogKiAgMS4gTGl0IGxhIGNvbmZpZ3VyYXRpb24gZGFucyAlQVBQ
REFUQSVcVFBFLUJyaWRnZVxjb25maWcuanNvbgogKiAgMi4gU2kgZWxsZSBuJ2V4
aXN0ZSBwYXMgKHByZW1pZXIgbGFuY2VtZW50KSA6IG91dnJlIHVuIHBldGl0IGFz
c2lzdGFudAogKiAgICAgZGFucyBsYSBjb25zb2xlIChVUkwgZGUgbCdhcHAsIHNs
dWcgZHUgc2Fsb24sIGNsw6kgZHUgcG9udCwKICogICAgIGltcHJpbWFudGUgZmFj
dWx0YXRpdmUpLCBsYSBzYXV2ZWdhcmRlLCBldCBuZSByZWRlbWFuZGUgamFtYWlz
IHBsdXMKICogIDMuIETDqW1hcnJlIGxlIHBvbnQgKHBvbGxpbmcgc2VydmV1ciAr
IG9wdGlvbiBUUEUpIGVuIGFycmnDqHJlLXBsYW4sCiAqICAgICBhdmVjIHJlbGFu
Y2UgYXV0b21hdGlxdWUgZW4gY2FzIGRlIGNyYXNoLCBldCB1bmUgaWPDtG5lIHN5
c3TDqG1lCiAqICAgICBkaXNjcmV0IChjb25zb2xlIG1pbmltaXPDqWUpCiAqCiAq
IEwnaW5zdGFsbGF0ZXVyIChpbnN0YWxsLmJhdCkgY3LDqWUgdW4gcmFjY291cmNp
IGRhbnMgbGUgbWVudSBEw6ltYXJyZXIKICogZXQgbGUgbGFuY2UgYXUgZMOpbWFy
cmFnZSBkZSBXaW5kb3dzIOKAlCBsZSBjb2lmZmV1ciBuJ3kgdG91Y2hlIGphbWFp
cy4KICoKICogQ2UgZmljaGllciBFU1QgbGUgcG9udCA6IGlsIGVtYmFycXVlIHRv
dXRlIGxhIGxvZ2lxdWUgZGUKICogdHBlLWJyaWRnZS5qcyAoY2hhcmfDqSBwYXIg
cmVxdWlyZSBzaSBwcsOpc2VudCDDoCBjw7R0w6ksIHNpbm9uIGlsCiAqIGZvbmN0
aW9ubmUgZW4gbW9kZSBhdXRvbm9tZSBpbXByZXNzaW9uIHNldWxlKS4KICovCgon
dXNlIHN0cmljdCc7Cgpjb25zdCBmcyA9IHJlcXVpcmUoJ2ZzJyk7CmNvbnN0IHBh
dGggPSByZXF1aXJlKCdwYXRoJyk7CmNvbnN0IHsgc3Bhd24sIGV4ZWNGaWxlU3lu
YyB9ID0gcmVxdWlyZSgnY2hpbGRfcHJvY2VzcycpOwpjb25zdCBvcyA9IHJlcXVp
cmUoJ29zJyk7Cgpjb25zdCBDT05GSUdfRElSID0gcGF0aC5qb2luKHByb2Nlc3Mu
ZW52LkFQUERBVEEgfHwgb3MuaG9tZWRpcigpLCAnVFBFLUJyaWRnZScpOwpjb25z
dCBDT05GSUdfRklMRSA9IHBhdGguam9pbihDT05GSUdfRElSLCAnY29uZmlnLmpz
b24nKTsKCi8qIC0tLS0tLS0tLS0gSm91cm5hbCAoJUFQUERBVEElXFRQRS1Ccmlk
Z2VcYnJpZGdlLmxvZykgLS0tLS0tLS0tLQogKiBMZSBwb250IHRvdXJuZSBzYW5z
IGZlbmV0cmUgOiBzYW5zIGpvdXJuYWwsIGltcG9zc2libGUgZGUgc2F2b2lyIHBv
dXJxdW9pIGlsCiAqIG5lIGRlbWFycmUgcGFzIG91IHMnYXJyZXRlLiBPbiBnYXJk
ZSBpY2kgY2UgcXVlIGxlIHBvbnQgYWZmaWNoZSwgcGx1cyBsZXMKICogZGVtYXJy
YWdlcy9hcnJldHMuIExlIGZpY2hpZXIgZXN0IGxpbWl0ZSAofjUwMCBLbywgdW4g
c2V1bCAub2xkIGNvbnNlcnZlKSBldAogKiB1biBwcm9ibGVtZSBkJ2Vjcml0dXJl
IG5lIGRvaXQgSkFNQUlTIGVtcGVjaGVyIGxlIHBvbnQgZGUgdG91cm5lci4gKi8K
Y29uc3QgTE9HX0ZJTEUgPSBwYXRoLmpvaW4oQ09ORklHX0RJUiwgJ2JyaWRnZS5s
b2cnKTsKbGV0IGxvZ1dyaXRlcyA9IDA7CmZ1bmN0aW9uIGxvZ1RleHQodGV4dCkg
ewogIHRyeSB7CiAgICBmcy5ta2RpclN5bmMoQ09ORklHX0RJUiwgeyByZWN1cnNp
dmU6IHRydWUgfSk7CiAgICBpZiAobG9nV3JpdGVzKysgJSAyMDAgPT09IDApIHsK
ICAgICAgdHJ5IHsgaWYgKGZzLnN0YXRTeW5jKExPR19GSUxFKS5zaXplID4gNTAw
MDAwKSBmcy5yZW5hbWVTeW5jKExPR19GSUxFLCBMT0dfRklMRSArICcub2xkJyk7
IH0gY2F0Y2ggKGUpIHsgLyogcGFzIGVuY29yZSBkZSBmaWNoaWVyICovIH0KICAg
IH0KICAgIGZzLmFwcGVuZEZpbGVTeW5jKExPR19GSUxFLCB0ZXh0KTsKICB9IGNh
dGNoIChlKSB7IC8qIGphbWFpcyBibG9xdWFudCAqLyB9Cn0KZnVuY3Rpb24gbG9n
TGluZShtc2cpIHsKICBsb2dUZXh0KCdbJyArIG5ldyBEYXRlKCkudG9Mb2NhbGVT
dHJpbmcoJ2ZyLUZSJykgKyAnXSAnICsgbXNnICsgJ1xuJyk7Cn0KCi8qIC0tLS0t
LS0tLS0gQ29uZmlndXJhdGlvbiAtLS0tLS0tLS0tICovCgpmdW5jdGlvbiBsb2Fk
Q29uZmlnKCkgewogIHRyeSB7CiAgICBsZXQgcmF3ID0gZnMucmVhZEZpbGVTeW5j
KENPTkZJR19GSUxFLCAndXRmOCcpOwogICAgLy8gVG9sZXJlIHVuIEJPTSBVVEYt
OCBlbiB0ZXRlIGRlIGZpY2hpZXIgKHByZXNlbnQgc2kgbGUgZmljaGllciBhIGV0
ZQogICAgLy8gZWNyaXQgcGFyICJTZXQtQ29udGVudCAtRW5jb2RpbmcgVVRGOCIg
c291cyBXaW5kb3dzIFBvd2VyU2hlbGwgNS4xLAogICAgLy8gcXVpIGwnYWpvdXRl
IHNpbGVuY2lldXNlbWVudCkgLSBzaW5vbiBKU09OLnBhcnNlIGVjaG91ZSBldCBv
bgogICAgLy8gcmV0b21iZSBhIHRvcnQgc3VyIGwnYXNzaXN0YW50IGRlIHByZW1p
ZXJlIGNvbmZpZ3VyYXRpb24gYWxvcnMgcXVlCiAgICAvLyBsYSBjb25maWcgZXhp
c3RlIGRlamEgZXQgZXN0IHZhbGlkZS4KICAgIGlmIChyYXcuY2hhckNvZGVBdCgw
KSA9PT0gMHhGRUZGKSByYXcgPSByYXcuc2xpY2UoMSk7CiAgICByZXR1cm4gSlNP
Ti5wYXJzZShyYXcpOwogIH0gY2F0Y2ggKGUpIHsKICAgIHJldHVybiBudWxsOwog
IH0KfQoKZnVuY3Rpb24gc2F2ZUNvbmZpZyhjZmcpIHsKICBmcy5ta2RpclN5bmMo
Q09ORklHX0RJUiwgeyByZWN1cnNpdmU6IHRydWUgfSk7CiAgZnMud3JpdGVGaWxl
U3luYyhDT05GSUdfRklMRSwgSlNPTi5zdHJpbmdpZnkoY2ZnLCBudWxsLCAyKSwg
J3V0ZjgnKTsKfQoKZnVuY3Rpb24gYXNrKHJsLCBxdWVzdGlvbiwgZGVmKSB7CiAg
cmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlKSA9PiB7CiAgICBjb25zdCBzdWZm
aXggPSBkZWYgPyBgICgke2RlZn0pYCA6ICcnOwogICAgcmwucXVlc3Rpb24ocXVl
c3Rpb24gKyBzdWZmaXggKyAnIDogJywgKGFuc3dlcikgPT4gewogICAgICByZXNv
bHZlKFN0cmluZyhhbnN3ZXIgfHwgJycpLnRyaW0oKSB8fCBkZWYgfHwgJycpOwog
ICAgfSk7CiAgfSk7Cn0KCi8qKgogKiBQYXJ0YWdlIGF1dG9tYXRpcXVlbWVudCBs
J2ltcHJpbWFudGUgcGFyIGTDqWZhdXQgZGUgV2luZG93cyB2aWEKICogUG93ZXJT
aGVsbCAoU2V0LVByaW50ZXIgLVNoYXJlZCksIHBvdXIgw6l2aXRlciBsYSBtYW5p
cHVsYXRpb24KICogbWFudWVsbGUgKFByb3ByacOpdMOpcyBkZSBsJ2ltcHJpbWFu
dGUgPiBQYXJ0YWdlID4gY29jaGVyIGxhIGNhc2UsCiAqIHBhcmZvaXMgZGlmZmlj
aWxlIMOgIHRyb3V2ZXIpLiBSZXRvdXJuZSBsZSBub20gZGUgcGFydGFnZSB1dGls
aXPDqSwgb3UKICogbnVsbCBzaSDDp2Egw6ljaG91ZSAoaW1wcmltYW50ZSBpbnRy
b3V2YWJsZSwgZHJvaXRzIGluc3VmZmlzYW50cy4uLikgLQogKiBkYW5zIGNlIGNh
cyBsJ3V0aWxpc2F0ZXVyIHBldXQgdG91am91cnMgcGFydGFnZXIgbWFudWVsbGVt
ZW50CiAqICh2b2lyIHdpbmRvd3MvUkVBRE1FLm1kKSBldCBzYWlzaXIgbGUgbm9t
IGRlIHBhcnRhZ2Ugw6AgbGEgcXVlc3Rpb24KICogc3VpdmFudGUuCiAqLwpmdW5j
dGlvbiBhdXRvU2hhcmVEZWZhdWx0UHJpbnRlcigpIHsKICB0cnkgewogICAgY29u
c3Qgc2NyaXB0ID0KICAgICAgJyRwID0gR2V0LUNpbUluc3RhbmNlIC1DbGFzc05h
bWUgV2luMzJfUHJpbnRlciB8IFdoZXJlLU9iamVjdCB7ICRfLkRlZmF1bHQgLWVx
ICR0cnVlIH0gfCBTZWxlY3QtT2JqZWN0IC1GaXJzdCAxOyAnICsKICAgICAgJ2lm
ICgkcCkgeyAnICsKICAgICAgJyAgJHNoYXJlID0gKCRwLk5hbWUgLXJlcGxhY2Ug
IlteYS16QS1aMC05Xy1dIiwgIl8iKTsgJyArCiAgICAgICcgIGlmICgkc2hhcmUu
TGVuZ3RoIC1lcSAwKSB7ICRzaGFyZSA9ICJUaWNrZXRQcmludGVyIiB9OyAnICsK
ICAgICAgJyAgU2V0LVByaW50ZXIgLU5hbWUgJHAuTmFtZSAtU2hhcmVkICR0cnVl
IC1TaGFyZU5hbWUgJHNoYXJlIC1FcnJvckFjdGlvbiBTdG9wOyAnICsKICAgICAg
JyAgV3JpdGUtT3V0cHV0ICgkcC5OYW1lICsgInwiICsgJHNoYXJlKSAnICsKICAg
ICAgJ30nOwogICAgY29uc3Qgb3V0ID0gZXhlY0ZpbGVTeW5jKCdwb3dlcnNoZWxs
LmV4ZScsIFsnLU5vUHJvZmlsZScsICctQ29tbWFuZCcsIHNjcmlwdF0sIHsgZW5j
b2Rpbmc6ICd1dGY4JywgdGltZW91dDogMTAwMDAgfSkudHJpbSgpOwogICAgaWYg
KCFvdXQpIHJldHVybiBudWxsOwogICAgY29uc3QgW3ByaW50ZXJOYW1lLCBzaGFy
ZU5hbWVdID0gb3V0LnNwbGl0KCd8Jyk7CiAgICByZXR1cm4geyBwcmludGVyTmFt
ZSwgc2hhcmVOYW1lIH07CiAgfSBjYXRjaCAoZSkgewogICAgcmV0dXJuIG51bGw7
CiAgfQp9CgovKiogQXNzaXN0YW50IGRlIHByZW1pZXIgbGFuY2VtZW50IDogcG9z
ZSBsZXMgNCBxdWVzdGlvbnMgZXQgc2F1dmVnYXJkZS4gKi8KYXN5bmMgZnVuY3Rp
b24gZmlyc3RSdW5XaXphcmQoKSB7CiAgY29uc29sZS5sb2coJycpOwogIGNvbnNv
bGUubG9nKCc9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
PT09PT09PT0nKTsKICBjb25zb2xlLmxvZygnICAgVFBFIEJyaWRnZSAtIFByZW1p
ZXJlIGNvbmZpZ3VyYXRpb24nKTsKICBjb25zb2xlLmxvZygnPT09PT09PT09PT09
PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09Jyk7CiAgY29uc29s
ZS5sb2coJycpOwogIGNvbnNvbGUubG9nKCdCaWVudmVudWUgISBDZSBwcm9ncmFt
bWUgcmVsaWUgdm90cmUgY2Fpc3NlIGVuIGxpZ25lIGEnKTsKICBjb25zb2xlLmxv
Zygndm90cmUgaW1wcmltYW50ZSBldCB0ZXJtaW5hbCBkZSBwYWllbWVudC4gUmVw
b25kZXogYXV4Jyk7CiAgY29uc29sZS5sb2coJzMgcXVlc3Rpb25zIHN1aXZhbnRl
cyAodW5lIHNldWxlIGZvaXMpLicpOwogIGNvbnNvbGUubG9nKCcnKTsKICBjb25z
b2xlLmxvZygnKEFzdHVjZSA6IGxlcyAyIGRlcm5pZXJlcyB2b3VzIHNvbnQgZG9u
bmVlcyBwYXIgdm90cmUnKTsKICBjb25zb2xlLmxvZygnIHN1cHBvcnQsIGRhbnMg
bGUgRGFzaGJvYXJkID4gUmVnbGFnZXMgPiBUZXJtaW5hbCBkZScpOwogIGNvbnNv
bGUubG9nKCcgcGFpZW1lbnQsIGJvdXRvbiAiR2VuZXJlciBsYSBjbGUgZHUgcG9u
dCIuKScpOwogIGNvbnNvbGUubG9nKCcnKTsKCiAgY29uc29sZS5sb2coJ1suLl0g
UGFydGFnZSBkZSBsXCdpbXByaW1hbnRlIHBhciBkZWZhdXQgKGltcHJlc3Npb24g
c2lsZW5jaWV1c2UpLi4uJyk7CiAgY29uc3Qgc2hhcmVkID0gYXV0b1NoYXJlRGVm
YXVsdFByaW50ZXIoKTsKICBsZXQgZGVmYXVsdFByaW50ZXJBbnN3ZXIgPSAnJzsK
ICBpZiAoc2hhcmVkKSB7CiAgICBjb25zb2xlLmxvZygnW09LXSAiJyArIHNoYXJl
ZC5wcmludGVyTmFtZSArICciIHBhcnRhZ2VlIHNvdXMgbGUgbm9tICInICsgc2hh
cmVkLnNoYXJlTmFtZSArICciLicpOwogICAgZGVmYXVsdFByaW50ZXJBbnN3ZXIg
PSBzaGFyZWQuc2hhcmVOYW1lOwogIH0gZWxzZSB7CiAgICBjb25zb2xlLmxvZygn
WyFdIFBhcnRhZ2UgYXV0b21hdGlxdWUgaW1wb3NzaWJsZSAoYXVjdW5lIGltcHJp
bWFudGUgcGFyIGRlZmF1dCwgb3UgZHJvaXRzJyk7CiAgICBjb25zb2xlLmxvZygn
ICAgIGluc3VmZmlzYW50cyAtIHJlbGFuY2V6IGVuIHRhbnQgcXVcJ2FkbWluaXN0
cmF0ZXVyKS4gVm91cyBwb3V2ZXogcGFydGFnZXInKTsKICAgIGNvbnNvbGUubG9n
KCcgICAgbFwnaW1wcmltYW50ZSBtYW51ZWxsZW1lbnQgKHZvaXIgd2luZG93cy9S
RUFETUUubWQpIGV0IGluZGlxdWVyIHNvbiBub20nKTsKICAgIGNvbnNvbGUubG9n
KCcgICAgZGUgcGFydGFnZSBhIGxhIHF1ZXN0aW9uIHN1aXZhbnRlLCBvdSByZWVz
c2F5ZXIgcGx1cyB0YXJkLicpOwogIH0KICBjb25zb2xlLmxvZygnJyk7CgogIGNv
bnN0IHJlYWRsaW5lID0gcmVxdWlyZSgncmVhZGxpbmUnKTsKICBjb25zdCBybCA9
IHJlYWRsaW5lLmNyZWF0ZUludGVyZmFjZSh7IGlucHV0OiBwcm9jZXNzLnN0ZGlu
LCBvdXRwdXQ6IHByb2Nlc3Muc3Rkb3V0IH0pOwoKICBjb25zdCBzZXJ2ZXIgPSBh
d2FpdCBhc2socmwsICdBZHJlc3NlIGRlIHZvdHJlIGFwcGxpY2F0aW9uIChleDog
aHR0cHM6Ly9yZHYuaGFuZHNncmFwaGljLmNvbSknLCAnaHR0cHM6Ly9yZHYuaGFu
ZHNncmFwaGljLmNvbScpOwogIGNvbnN0IHNhbG9uID0gYXdhaXQgYXNrKHJsLCAn
SWRlbnRpZmlhbnQgZHUgc2Fsb24gKGNlbHVpIGRhbnMgbFwnVVJMID9zYWxvbj0u
Li4pJywgJycpOwogIGNvbnN0IGtleSA9IGF3YWl0IGFzayhybCwgJ0NsZSBkdSBw
b250JywgJycpOwogIGNvbnN0IHByaW50ZXIgPSBhd2FpdCBhc2socmwsICdOb20g
ZGUgcGFydGFnZSBkZSBsXCdpbXByaW1hbnRlJywgZGVmYXVsdFByaW50ZXJBbnN3
ZXIpOwogIGNvbnN0IHRwZUlwID0gYXdhaXQgYXNrKHJsLCAnSVAgZHUgVFBFIChF
bnRyZWUgc2kgYXVjdW4gVFBFIHBvdXIgbGUgbW9tZW50KScsICcnKTsKICBybC5j
bG9zZSgpOwoKICBpZiAoIXNhbG9uIHx8ICFrZXkpIHsKICAgIGNvbnNvbGUubG9n
KCcnKTsKICAgIGNvbnNvbGUubG9nKCdbIV0gTFwnaWRlbnRpZmlhbnQgZHUgc2Fs
b24gZXQgbGEgY2xlIGR1IHBvbnQgc29udCBvYmxpZ2F0b2lyZXMuJyk7CiAgICBj
b25zb2xlLmxvZygnICAgIFJlbGFuY2V6IGNlIHByb2dyYW1tZSBwb3VyIHJlY29t
bWVuY2VyLicpOwogICAgcHJvY2Vzcy5leGl0KDEpOwogIH0KCiAgY29uc3QgY2Zn
ID0geyBzZXJ2ZXIsIHNhbG9uLCBrZXksIHByaW50ZXIsIHRwZUlwIH07CiAgc2F2
ZUNvbmZpZyhjZmcpOwogIGNvbnNvbGUubG9nKCcnKTsKICBjb25zb2xlLmxvZygn
W09LXSBDb25maWd1cmF0aW9uIHNhdXZlZ2FyZGVlIDogJyArIENPTkZJR19GSUxF
KTsKICBjb25zb2xlLmxvZygnJyk7CiAgcmV0dXJuIGNmZzsKfQoKLyogLS0tLS0t
LS0tLSBEw6ltYXJyYWdlIGR1IHBvbnQgLS0tLS0tLS0tLSAqLwoKZnVuY3Rpb24g
c3RhcnRCcmlkZ2UoY2ZnKSB7CiAgY29uc3QgYXJncyA9IFsKICAgICctLXNlcnZl
cicsIGNmZy5zZXJ2ZXIsCiAgICAnLS1zYWxvbicsIGNmZy5zYWxvbiwKICAgICct
LWtleScsIGNmZy5rZXkKICBdOwogIGlmIChjZmcucHJpbnRlcikgYXJncy5wdXNo
KCctLXByaW50ZXInLCBjZmcucHJpbnRlcik7CiAgaWYgKGNmZy50cGVJcCkgYXJn
cy5wdXNoKCctLXRwZScsIGNmZy50cGVJcCk7CiAgaWYgKGNmZy50cGVQb3MpIGFy
Z3MucHVzaCgnLS1wb3MnLCBjZmcudHBlUG9zKTsKCiAgLy8gUmVsYW5jZSBhdXRv
bWF0aXF1ZSA6IHNpIGxlIHByb2Nlc3MgbWV1cnQgKGNyYXNoLCBNQUogcsOpc2Vh
dS4uLiksCiAgLy8gb24gbGUgcmVsYW5jZSBhcHLDqHMgNSBzLCBpbmTDqWZpbmlt
ZW50LgogIGNvbnN0IGNoaWxkID0gc3Bhd24ocHJvY2Vzcy5leGVjUGF0aCwgW3Bh
dGguam9pbihfX2Rpcm5hbWUsICdicmlkZ2UtY29yZS5qcycpLCAuLi5hcmdzXSwg
ewogICAgc3RkaW86IFsnaWdub3JlJywgJ3BpcGUnLCAncGlwZSddLAogICAgd2lu
ZG93c0hpZGU6IHRydWUKICB9KTsKICBsb2dMaW5lKCdjb2V1ciBkdSBwb250IGRl
bWFycmUgKHBpZCAnICsgY2hpbGQucGlkICsgJyknKTsKCiAgLy8gQ2UgcXVlIGxl
IHBvbnQgYWZmaWNoZSB2YSBhIGxhIGNvbnNvbGUgKHNpIGVsbGUgZXN0IHZpc2li
bGUpIEVUIGF1IGpvdXJuYWwuCiAgY2hpbGQuc3Rkb3V0Lm9uKCdkYXRhJywgKGQp
ID0+IHsgdHJ5IHsgcHJvY2Vzcy5zdGRvdXQud3JpdGUoZCk7IH0gY2F0Y2ggKGUp
IHsgLyogY29uc29sZSBhYnNlbnRlICovIH0gbG9nVGV4dChkLnRvU3RyaW5nKCkp
OyB9KTsKICBjaGlsZC5zdGRlcnIub24oJ2RhdGEnLCAoZCkgPT4geyB0cnkgeyBw
cm9jZXNzLnN0ZGVyci53cml0ZShkKTsgfSBjYXRjaCAoZSkgeyAvKiBjb25zb2xl
IGFic2VudGUgKi8gfSBsb2dUZXh0KGQudG9TdHJpbmcoKSk7IH0pOwoKICAvLyAn
ZXJyb3InIChsYW5jZW1lbnQgaW1wb3NzaWJsZSkgZXQgJ2V4aXQnIHBldXZlbnQg
bCd1biBjb21tZSBsJ2F1dHJlCiAgLy8gc3VydmVuaXIgc2V1bHMgOiBkYW5zIGxl
cyBkZXV4IGNhcyBvbiByZWxhbmNlLCB1bmUgc2V1bGUgZm9pcy4KICBsZXQgcmVz
dGFydFNjaGVkdWxlZCA9IGZhbHNlOwogIGNvbnN0IHJlc3RhcnQgPSAoKSA9PiB7
CiAgICBpZiAocmVzdGFydFNjaGVkdWxlZCkgcmV0dXJuOwogICAgcmVzdGFydFNj
aGVkdWxlZCA9IHRydWU7CiAgICBzZXRUaW1lb3V0KCgpID0+IHN0YXJ0QnJpZGdl
KGNmZyksIDUwMDApOwogIH07CgogIGNoaWxkLm9uKCdlcnJvcicsIChlcnIpID0+
IHsKICAgIGxvZ0xpbmUoJ2ltcG9zc2libGUgZGUgbGFuY2VyIGxlIGNvZXVyIGR1
IHBvbnQgOiAnICsgZXJyLm1lc3NhZ2UgKyAnIC0gbm91dmVsIGVzc2FpIGRhbnMg
NSBzJyk7CiAgICByZXN0YXJ0KCk7CiAgfSk7CgogIGNoaWxkLm9uKCdleGl0Jywg
KGNvZGUpID0+IHsKICAgIGxvZ0xpbmUoJ3BvbnQgYXJyZXRlIChjb2RlICcgKyBj
b2RlICsgJykgLSByZWxhbmNlIGRhbnMgNSBzJyk7CiAgICBjb25zb2xlLmxvZyhg
W2ldIFBvbnQgYXJyw6p0w6kgKGNvZGUgJHtjb2RlfSkg4oCUIHJlbGFuY2UgZGFu
cyA1IHMuLi4gKEN0cmwrQyBkZXV4IGZvaXMgcG91ciBxdWl0dGVyKWApOwogICAg
cmVzdGFydCgpOwogIH0pOwp9CgovKiAtLS0tLS0tLS0tIE1haW4gLS0tLS0tLS0t
LSAqLwoKYXN5bmMgZnVuY3Rpb24gbWFpbigpIHsKICBsZXQgd2hvID0gJz8nOwog
IHRyeSB7IHdobyA9IG9zLnVzZXJJbmZvKCkudXNlcm5hbWU7IH0gY2F0Y2ggKGUp
IHsgLyogcmFyZSAqLyB9CiAgbG9nTGluZSgnbGFuY2V1ciBXaW5kb3dzIGRlbWFy
cmUgKHBpZCAnICsgcHJvY2Vzcy5waWQgKyAnLCB1dGlsaXNhdGV1ciAnICsgd2hv
ICsgJyknKTsKICBsZXQgY2ZnID0gbG9hZENvbmZpZygpOwogIGlmICghY2ZnKSB7
CiAgICBjZmcgPSBhd2FpdCBmaXJzdFJ1bldpemFyZCgpOwogIH0KCiAgY29uc29s
ZS5sb2coJycpOwogIGNvbnNvbGUubG9nKCc9PT0gVFBFIEJyaWRnZSA9PT0nKTsK
ICBjb25zb2xlLmxvZyhgQXBwICAgICAgOiAke2NmZy5zZXJ2ZXJ9YCk7CiAgY29u
c29sZS5sb2coYFNhbG9uICAgIDogJHtjZmcuc2Fsb259YCk7CiAgY29uc29sZS5s
b2coYENvbmZpZyAgIDogJHtDT05GSUdfRklMRX1gKTsKICBjb25zb2xlLmxvZygn
Jyk7CgogIC8vIExlIGPFk3VyIGR1IHBvbnQgZXN0IGRhbnMgYnJpZGdlLWNvcmUu
anMgKG3Dqm1lIGRvc3NpZXIpIDogYydlc3QgbGUKICAvLyB0cGUtYnJpZGdlLmpz
IHN0YW5kYXJkIHJlbm9tbcOpLiBPbiBsZSBSRUNPUElFIMOAIENIQVFVRSBEw4lN
QVJSQUdFIGRlcHVpcwogIC8vIHRwZS1icmlkZ2UuanMgKGZvdXJuaSBwYXIgbCdp
bnN0YWxsYXRldXIpIDogYXZhbnQsIGlsIG4nw6l0YWl0IGNyw6nDqSBxdWUKICAv
LyBzJ2lsIG1hbnF1YWl0LCBkb25jIHVuZSBtaXNlIMOgIGpvdXIgZGUgdHBlLWJy
aWRnZS5qcyAoZXg6IGNvcnJlY3RpZgogIC8vIGQnZW5jb2RhZ2UgZGVzIHRpY2tl
dHMpIG4nw6l0YWl0IGphbWFpcyBhcHBsaXF1w6llIC0gbGUgcG9udCBjb250aW51
YWl0IMOgCiAgLy8gZmFpcmUgdG91cm5lciBsJ2FuY2llbm5lIGNvcGllIGluZMOp
ZmluaW1lbnQuCiAgY29uc3QgY29yZVBhdGggPSBwYXRoLmpvaW4oX19kaXJuYW1l
LCAnYnJpZGdlLWNvcmUuanMnKTsKICBjb25zdCBzcmMgPSBwYXRoLmpvaW4oX19k
aXJuYW1lLCAndHBlLWJyaWRnZS5qcycpOwogIGlmIChmcy5leGlzdHNTeW5jKHNy
YykpIHsKICAgIHRyeSB7IGZzLmNvcHlGaWxlU3luYyhzcmMsIGNvcmVQYXRoKTsg
fSBjYXRjaCAoZSkgeyAvKiBvbiBnYXJkZSBsYSBjb3BpZSBleGlzdGFudGUgKi8g
fQogIH0KICBpZiAoIWZzLmV4aXN0c1N5bmMoY29yZVBhdGgpKSB7CiAgICBjb25z
b2xlLmVycm9yKCdbIV0gYnJpZGdlLWNvcmUuanMgaW50cm91dmFibGUg4oCUIHLD
qWluc3RhbGxleiBUUEUgQnJpZGdlLicpOwogICAgcHJvY2Vzcy5leGl0KDEpOwog
IH0KCiAgc3RhcnRCcmlkZ2UoY2ZnKTsKfQoKbWFpbigpLmNhdGNoKChlcnIpID0+
IHsKICBjb25zb2xlLmVycm9yKCdbIV0gRXJyZXVyIGZhdGFsZSA6JywgZXJyLm1l
c3NhZ2UpOwogIGxvZ0xpbmUoJ0VSUkVVUiBGQVRBTEUgOiAnICsgKGVyciAmJiBl
cnIuc3RhY2sgPyBlcnIuc3RhY2sgOiBlcnIpKTsKICBwcm9jZXNzLmV4aXQoMSk7
Cn0pOw==
-----END CERTIFICATE-----
:TPE_BRIDGE_WIN_END
:CONFIG_WIZARD_BEGIN
-----BEGIN CERTIFICATE-----
IyBQZXRpdGUgZmVuZXRyZSBkZSBjb25maWd1cmF0aW9uIGR1IFRQRSBCcmlkZ2Us
IHBvdXIgdW4gY2xpZW50IG5vbgojIHRlY2huaXF1ZSA6IGNvbGxlciBsZSBzYWxv
biArIGxhIGNsZSBkYW5zIGRldXggY2hhbXBzIGRlIHRleHRlCiMgbm9ybWF1eCAo
Y29waWVyL2NvbGxlciBzdGFuZGFyZCBXaW5kb3dzLCBwYXMgZGUgdGVybWluYWws
IHBhcyBkZQojIGZpY2hpZXIgYSBlZGl0ZXIgYSBsYSBtYWluKS4gVXRpbGlzZSB1
bmlxdWVtZW50IFdpbkZvcm1zIChkZWphCiMgcHJlc2VudCBzdXIgdG91dCBXaW5k
b3dzIHZpYSAuTkVUKSwgYXVjdW5lIGRlcGVuZGFuY2UgYSBpbnN0YWxsZXIuCgpB
ZGQtVHlwZSAtQXNzZW1ibHlOYW1lIFN5c3RlbS5XaW5kb3dzLkZvcm1zCkFkZC1U
eXBlIC1Bc3NlbWJseU5hbWUgU3lzdGVtLkRyYXdpbmcKCiRjb25maWdEaXIgPSBK
b2luLVBhdGggJGVudjpBUFBEQVRBICJUUEUtQnJpZGdlIgokY29uZmlnRmlsZSA9
IEpvaW4tUGF0aCAkY29uZmlnRGlyICJjb25maWcuanNvbiIKCiMgVGVudGUgZGUg
cGFydGFnZXIgbCdpbXByaW1hbnRlIHBhciBkZWZhdXQgYXV0b21hdGlxdWVtZW50
IChpbXByZXNzaW9uCiMgc2lsZW5jaWV1c2UsIHNhbnMgamFtYWlzIG91dnJpciBk
ZSBmZW5ldHJlKSAtIHZvaXIgdHBlLWJyaWRnZS5qcyBwb3VyCiMgbGUgZGV0YWls
IGRlIHBvdXJxdW9pIGMnZXN0IG5lY2Vzc2FpcmUgc291cyBXaW5kb3dzLiBTaW1w
bGUgYm9udXMgaWNpIDoKIyBzaSBjYSByZXVzc2l0LCBsZSBub20gZGUgcGFydGFn
ZSB0cm91dmUgcHJlLXJlbXBsaXQgbGUgY2hhbXAgaW1wcmltYW50ZS4KZnVuY3Rp
b24gR2V0LUF1dG9TaGFyZWRQcmludGVyTmFtZSB7CiAgICB0cnkgewogICAgICAg
ICRwID0gR2V0LUNpbUluc3RhbmNlIC1DbGFzc05hbWUgV2luMzJfUHJpbnRlciAt
RXJyb3JBY3Rpb24gU3RvcCB8IFdoZXJlLU9iamVjdCB7ICRfLkRlZmF1bHQgLWVx
ICR0cnVlIH0gfCBTZWxlY3QtT2JqZWN0IC1GaXJzdCAxCiAgICAgICAgaWYgKCRw
KSB7CiAgICAgICAgICAgICRzaGFyZSA9ICgkcC5OYW1lIC1yZXBsYWNlICdbXmEt
ekEtWjAtOV8tXScsICdfJykKICAgICAgICAgICAgaWYgKCRzaGFyZS5MZW5ndGgg
LWVxIDApIHsgJHNoYXJlID0gIlRpY2tldFByaW50ZXIiIH0KICAgICAgICAgICAg
U2V0LVByaW50ZXIgLU5hbWUgJHAuTmFtZSAtU2hhcmVkICR0cnVlIC1TaGFyZU5h
bWUgJHNoYXJlIC1FcnJvckFjdGlvbiBTdG9wCiAgICAgICAgICAgIHJldHVybiAk
c2hhcmUKICAgICAgICB9CiAgICB9IGNhdGNoIHt9CiAgICByZXR1cm4gIiIKfQoK
JGV4aXN0aW5nQ2ZnID0gJG51bGwKaWYgKFRlc3QtUGF0aCAkY29uZmlnRmlsZSkg
ewogICAgdHJ5IHsgJGV4aXN0aW5nQ2ZnID0gR2V0LUNvbnRlbnQgJGNvbmZpZ0Zp
bGUgLVJhdyB8IENvbnZlcnRGcm9tLUpzb24gfSBjYXRjaCB7fQp9CgokYXV0b1No
YXJlID0gR2V0LUF1dG9TaGFyZWRQcmludGVyTmFtZQppZiAoW3N0cmluZ106Oklz
TnVsbE9yV2hpdGVTcGFjZSgkYXV0b1NoYXJlKSAtYW5kICRleGlzdGluZ0NmZykg
eyAkYXV0b1NoYXJlID0gJGV4aXN0aW5nQ2ZnLnByaW50ZXIgfQoKJGZvcm0gPSBO
ZXctT2JqZWN0IFN5c3RlbS5XaW5kb3dzLkZvcm1zLkZvcm0KJGZvcm0uVGV4dCA9
ICJUUEUgQnJpZGdlIC0gQ29uZmlndXJhdGlvbiIKJGZvcm0uU2l6ZSA9IFtTeXN0
ZW0uRHJhd2luZy5TaXplXTo6bmV3KDQ4MCwgNTEwKQokZm9ybS5TdGFydFBvc2l0
aW9uID0gIkNlbnRlclNjcmVlbiIKJGZvcm0uRm9ybUJvcmRlclN0eWxlID0gIkZp
eGVkRGlhbG9nIgokZm9ybS5NYXhpbWl6ZUJveCA9ICRmYWxzZQokZm9ybS5NaW5p
bWl6ZUJveCA9ICRmYWxzZQoKJHRpdGxlID0gTmV3LU9iamVjdCBTeXN0ZW0uV2lu
ZG93cy5Gb3Jtcy5MYWJlbAokdGl0bGUuVGV4dCA9ICJDb25maWd1cmVyIGxhIGNh
aXNzZSBkZSBjZSBzYWxvbiIKJHRpdGxlLkZvbnQgPSBbU3lzdGVtLkRyYXdpbmcu
Rm9udF06Om5ldygiU2Vnb2UgVUkiLCAxMiwgW1N5c3RlbS5EcmF3aW5nLkZvbnRT
dHlsZV06OkJvbGQpCiR0aXRsZS5Mb2NhdGlvbiA9IFtTeXN0ZW0uRHJhd2luZy5Q
b2ludF06Om5ldygyMCwgMTUpCiR0aXRsZS5TaXplID0gW1N5c3RlbS5EcmF3aW5n
LlNpemVdOjpuZXcoNDMwLCAyNikKJGZvcm0uQ29udHJvbHMuQWRkKCR0aXRsZSkK
CmZ1bmN0aW9uIEFkZC1GaWVsZCgkbGFiZWxUZXh0LCAkeSwgJGRlZmF1bHRWYWx1
ZSkgewogICAgJGxhYmVsID0gTmV3LU9iamVjdCBTeXN0ZW0uV2luZG93cy5Gb3Jt
cy5MYWJlbAogICAgJGxhYmVsLlRleHQgPSAkbGFiZWxUZXh0CiAgICAkbGFiZWwu
TG9jYXRpb24gPSBbU3lzdGVtLkRyYXdpbmcuUG9pbnRdOjpuZXcoMjAsICR5KQog
ICAgJGxhYmVsLlNpemUgPSBbU3lzdGVtLkRyYXdpbmcuU2l6ZV06Om5ldyg0MzAs
IDE4KQogICAgJGZvcm0uQ29udHJvbHMuQWRkKCRsYWJlbCkKCiAgICAkdGV4dGJv
eCA9IE5ldy1PYmplY3QgU3lzdGVtLldpbmRvd3MuRm9ybXMuVGV4dEJveAogICAg
JHRleHRib3guTG9jYXRpb24gPSBbU3lzdGVtLkRyYXdpbmcuUG9pbnRdOjpuZXco
MjAsICR5ICsgMjApCiAgICAkdGV4dGJveC5TaXplID0gW1N5c3RlbS5EcmF3aW5n
LlNpemVdOjpuZXcoNDIwLCAyNCkKICAgICR0ZXh0Ym94LlRleHQgPSAkZGVmYXVs
dFZhbHVlCiAgICAkdGV4dGJveC5Gb250ID0gW1N5c3RlbS5EcmF3aW5nLkZvbnRd
OjpuZXcoIlNlZ29lIFVJIiwgMTApCiAgICAkZm9ybS5Db250cm9scy5BZGQoJHRl
eHRib3gpCiAgICByZXR1cm4gJHRleHRib3gKfQoKJGRlZmF1bHRTZXJ2ZXIgPSBp
ZiAoJGV4aXN0aW5nQ2ZnKSB7ICRleGlzdGluZ0NmZy5zZXJ2ZXIgfSBlbHNlIHsg
Imh0dHBzOi8vcmR2LmhhbmRzZ3JhcGhpYy5jb20iIH0KJGRlZmF1bHRTYWxvbiA9
IGlmICgkZXhpc3RpbmdDZmcpIHsgJGV4aXN0aW5nQ2ZnLnNhbG9uIH0gZWxzZSB7
ICIiIH0KJGRlZmF1bHRUcGVJcCA9IGlmICgkZXhpc3RpbmdDZmcpIHsgJGV4aXN0
aW5nQ2ZnLnRwZUlwIH0gZWxzZSB7ICIiIH0KIyBMZSBwb250IHMnYXR0ZW5kIGF1
IG1lbWUgbnVtZXJvIGRlIGNhaXNzZSBxdWUgY2VsdWkgYWZmaWNoZSBzdXIgbGUK
IyB0aWNrZXQgZGUgY29uZmlndXJhdGlvbiBkdSBUUEUgKG1lbnUgdGVjaG5pcXVl
IGR1IHRlcm1pbmFsKSAtICIyIiBlc3QKIyBsYSB2YWxldXIgbGEgcGx1cyBjb3Vy
YW50ZSwgZ2FyZGVlIHBhciBkZWZhdXQgcG91ciBuZSByaWVuIGNoYW5nZXIgYXV4
CiMgaW5zdGFsbGF0aW9ucyBleGlzdGFudGVzIHF1aSBtYXJjaGFpZW50IGRlamEg
YXZlYyBjZSByZWdsYWdlLgokZGVmYXVsdFRwZVBvcyA9IGlmICgkZXhpc3RpbmdD
ZmcgLWFuZCAkZXhpc3RpbmdDZmcudHBlUG9zKSB7ICRleGlzdGluZ0NmZy50cGVQ
b3MgfSBlbHNlIHsgIjIiIH0KCiR0YlNlcnZlciA9IEFkZC1GaWVsZCAiQWRyZXNz
ZSBkZSB2b3RyZSBhcHBsaWNhdGlvbiIgNTUgJGRlZmF1bHRTZXJ2ZXIKJHRiU2Fs
b24gPSBBZGQtRmllbGQgIklkZW50aWZpYW50IGR1IHNhbG9uIChjZWx1aSBkYW5z
IGwnVVJMID9zYWxvbj0uLi4pIiAxMDUgJGRlZmF1bHRTYWxvbgokdGJLZXkgPSBB
ZGQtRmllbGQgIkNsZSBkdSBwb250IChEYXNoYm9hcmQgPiBSZWdsYWdlcyA+IFRl
cm1pbmFsIGRlIHBhaWVtZW50KSIgMTU1ICIiCiR0YlByaW50ZXIgPSBBZGQtRmll
bGQgIk5vbSBkZSBwYXJ0YWdlIGRlIGwnaW1wcmltYW50ZSIgMjA1ICRhdXRvU2hh
cmUKJHRiVHBlSXAgPSBBZGQtRmllbGQgIklQIGR1IFRQRSAoZmFjdWx0YXRpZiwg
bGFpc3NlciB2aWRlIHNpIHBhcyBlbmNvcmUgY29uZmlndXJlKSIgMjU1ICRkZWZh
dWx0VHBlSXAKJHRiVHBlUG9zID0gQWRkLUZpZWxkICJOdW1lcm8gZGUgY2Fpc3Nl
IGR1IFRQRSAodm9pciBzb24gdGlja2V0LCBzb3V2ZW50IDIpIiAzMDUgJGRlZmF1
bHRUcGVQb3MKCiRsYmxTdGF0dXMgPSBOZXctT2JqZWN0IFN5c3RlbS5XaW5kb3dz
LkZvcm1zLkxhYmVsCiRsYmxTdGF0dXMuTG9jYXRpb24gPSBbU3lzdGVtLkRyYXdp
bmcuUG9pbnRdOjpuZXcoMjAsIDM1MCkKJGxibFN0YXR1cy5TaXplID0gW1N5c3Rl
bS5EcmF3aW5nLlNpemVdOjpuZXcoNDMwLCAyMCkKJGxibFN0YXR1cy5Gb3JlQ29s
b3IgPSBbU3lzdGVtLkRyYXdpbmcuQ29sb3JdOjpGaXJlYnJpY2sKJGZvcm0uQ29u
dHJvbHMuQWRkKCRsYmxTdGF0dXMpCgokYnRuT2sgPSBOZXctT2JqZWN0IFN5c3Rl
bS5XaW5kb3dzLkZvcm1zLkJ1dHRvbgokYnRuT2suVGV4dCA9ICJWYWxpZGVyIGV0
IGRlbWFycmVyIgokYnRuT2suTG9jYXRpb24gPSBbU3lzdGVtLkRyYXdpbmcuUG9p
bnRdOjpuZXcoMjAsIDM4MCkKJGJ0bk9rLlNpemUgPSBbU3lzdGVtLkRyYXdpbmcu
U2l6ZV06Om5ldygyMDAsIDM2KQokYnRuT2suRm9udCA9IFtTeXN0ZW0uRHJhd2lu
Zy5Gb250XTo6bmV3KCJTZWdvZSBVSSIsIDEwLCBbU3lzdGVtLkRyYXdpbmcuRm9u
dFN0eWxlXTo6Qm9sZCkKJGJ0bk9rLkFkZF9DbGljayh7CiAgICBpZiAoW3N0cmlu
Z106OklzTnVsbE9yV2hpdGVTcGFjZSgkdGJTYWxvbi5UZXh0KSAtb3IgW3N0cmlu
Z106OklzTnVsbE9yV2hpdGVTcGFjZSgkdGJLZXkuVGV4dCkpIHsKICAgICAgICAk
bGJsU3RhdHVzLlRleHQgPSAiTCdpZGVudGlmaWFudCBkdSBzYWxvbiBldCBsYSBj
bGUgZHUgcG9udCBzb250IG9ibGlnYXRvaXJlcy4iCiAgICAgICAgcmV0dXJuCiAg
ICB9CiAgICBOZXctSXRlbSAtSXRlbVR5cGUgRGlyZWN0b3J5IC1Gb3JjZSAtUGF0
aCAkY29uZmlnRGlyIHwgT3V0LU51bGwKICAgICRjZmcgPSBbb3JkZXJlZF1Aewog
ICAgICAgIHNlcnZlciAgPSAkdGJTZXJ2ZXIuVGV4dC5UcmltKCkKICAgICAgICBz
YWxvbiAgID0gJHRiU2Fsb24uVGV4dC5UcmltKCkKICAgICAgICBrZXkgICAgID0g
JHRiS2V5LlRleHQuVHJpbSgpCiAgICAgICAgcHJpbnRlciA9ICR0YlByaW50ZXIu
VGV4dC5UcmltKCkKICAgICAgICB0cGVJcCAgID0gJHRiVHBlSXAuVGV4dC5Ucmlt
KCkKICAgICAgICB0cGVQb3MgID0gJHRiVHBlUG9zLlRleHQuVHJpbSgpCiAgICB9
CiAgICAkanNvbiA9ICRjZmcgfCBDb252ZXJ0VG8tSnNvbgogICAgIyBTZXQtQ29u
dGVudCAtRW5jb2RpbmcgVVRGOCBham91dGUgdW4gQk9NIGludmlzaWJsZSBlbiB0
ZXRlIGRlIGZpY2hpZXIKICAgICMgc291cyBXaW5kb3dzIFBvd2VyU2hlbGwgNS4x
LCBjZSBxdWkgZmFpdCBlY2hvdWVyIEpTT04ucGFyc2UoKSBjb3RlCiAgICAjIE5v
ZGUuanMgKHRwZS1icmlkZ2Utd2luLmpzKSAtIG9uIGVjcml0IGRvbmMgbm91cy1t
ZW1lcyBlbiBVVEY4IFNBTlMgQk9NLgogICAgW1N5c3RlbS5JTy5GaWxlXTo6V3Jp
dGVBbGxUZXh0KCRjb25maWdGaWxlLCAkanNvbiwgW1N5c3RlbS5UZXh0LlVURjhF
bmNvZGluZ106Om5ldygkZmFsc2UpKQogICAgJGZvcm0uVGFnID0gIm9rIgogICAg
JGZvcm0uQ2xvc2UoKQp9KQokZm9ybS5Db250cm9scy5BZGQoJGJ0bk9rKQokZm9y
bS5BY2NlcHRCdXR0b24gPSAkYnRuT2sKCiRidG5DYW5jZWwgPSBOZXctT2JqZWN0
IFN5c3RlbS5XaW5kb3dzLkZvcm1zLkJ1dHRvbgokYnRuQ2FuY2VsLlRleHQgPSAi
QW5udWxlciIKJGJ0bkNhbmNlbC5Mb2NhdGlvbiA9IFtTeXN0ZW0uRHJhd2luZy5Q
b2ludF06Om5ldygyMzAsIDM4MCkKJGJ0bkNhbmNlbC5TaXplID0gW1N5c3RlbS5E
cmF3aW5nLlNpemVdOjpuZXcoMTIwLCAzNikKJGJ0bkNhbmNlbC5BZGRfQ2xpY2so
eyAkZm9ybS5UYWcgPSAiY2FuY2VsIjsgJGZvcm0uQ2xvc2UoKSB9KQokZm9ybS5D
b250cm9scy5BZGQoJGJ0bkNhbmNlbCkKCiRsYmxOb3RlID0gTmV3LU9iamVjdCBT
eXN0ZW0uV2luZG93cy5Gb3Jtcy5MYWJlbAokbGJsTm90ZS5UZXh0ID0gIkxhIGNs
ZSBldCBsJ2lkZW50aWZpYW50IGR1IHNhbG9uIHNlIHRyb3V2ZW50IGRhbnMgbGUg
RGFzaGJvYXJkLGBuc291cyBSZWdsYWdlcyA+IFRlcm1pbmFsIGRlIHBhaWVtZW50
ID4gR2VuZXJlciBsYSBjbGUgZHUgcG9udC4iCiRsYmxOb3RlLkxvY2F0aW9uID0g
W1N5c3RlbS5EcmF3aW5nLlBvaW50XTo6bmV3KDIwLCA0MjUpCiRsYmxOb3RlLlNp
emUgPSBbU3lzdGVtLkRyYXdpbmcuU2l6ZV06Om5ldyg0MzAsIDQwKQokbGJsTm90
ZS5Gb3JlQ29sb3IgPSBbU3lzdGVtLkRyYXdpbmcuQ29sb3JdOjpHcmF5CiRmb3Jt
LkNvbnRyb2xzLkFkZCgkbGJsTm90ZSkKClt2b2lkXSRmb3JtLlNob3dEaWFsb2co
KQoKaWYgKCRmb3JtLlRhZyAtZXEgIm9rIikgeyBleGl0IDAgfSBlbHNlIHsgZXhp
dCAxIH0K
-----END CERTIFICATE-----
:CONFIG_WIZARD_END
:CONFIGURER_BAT_BEGIN
-----BEGIN CERTIFICATE-----
QGVjaG8gb2ZmClJFTSBMYW5jZSBsZSBmb3JtdWxhaXJlIGdyYXBoaXF1ZSBkZSBj
b25maWd1cmF0aW9uIChjb25maWctd2l6YXJkLnBzMSksClJFTSBwdWlzIGRlbWFy
cmUgbGUgcG9udCBqdXN0ZSBhcHJlcyBzaSBsYSBjb25maWd1cmF0aW9uIGEgYmll
biBldGUKUkVNIHZhbGlkZWUgKHBhcyBiZXNvaW4gZCd1bmUgZXRhcGUgc2VwYXJl
ZSkuCnBvd2Vyc2hlbGwuZXhlIC1Ob1Byb2ZpbGUgLUV4ZWN1dGlvblBvbGljeSBC
eXBhc3MgLUZpbGUgIiV+ZHAwY29uZmlnLXdpemFyZC5wczEiCmlmICVlcnJvckxl
dmVsJSBuZXEgMCAoCiAgICBlY2hvIENvbmZpZ3VyYXRpb24gYW5udWxlZSAtIGxl
IHBvbnQgbidhIHBhcyBldGUgZGVtYXJyZS4KICAgIHBhdXNlCiAgICBleGl0IC9i
IDEKKQplY2hvIENvbmZpZ3VyYXRpb24gZW5yZWdpc3RyZWUsIGRlbWFycmFnZSBk
dSBwb250Li4uClJFTSBBcnJldGUgbCdhbmNpZW5uZSBpbnN0YW5jZSBhdmFudCBk
ZSByZWxhbmNlciwgc2lub24gMiBwb3V2YWllbnQgdG91cm5lcgpSRU0gZW4gbWVt
ZSB0ZW1wcyAobCd1bmUgdmlzaWJsZSByZXN0YW50ZSwgbCdhdXRyZSBub3V2ZWxs
ZSBpbnZpc2libGUpCnBvd2Vyc2hlbGwuZXhlIC1Ob1Byb2ZpbGUgLUNvbW1hbmQg
IkdldC1DaW1JbnN0YW5jZSBXaW4zMl9Qcm9jZXNzIC1GaWx0ZXIgXCJOYW1lPSdu
b2RlLmV4ZSdcIiAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZSB8IFdoZXJl
LU9iamVjdCB7ICRfLkNvbW1hbmRMaW5lIC1saWtlICcqdHBlLWJyaWRnZS13aW4u
anMqJyAtb3IgJF8uQ29tbWFuZExpbmUgLWxpa2UgJyp0cGUtYnJpZGdlLmpzKicg
fSB8IEZvckVhY2gtT2JqZWN0IHsgU3RvcC1Qcm9jZXNzIC1JZCAkXy5Qcm9jZXNz
SWQgLUZvcmNlIC1FcnJvckFjdGlvbiBTaWxlbnRseUNvbnRpbnVlIH0iID5udWwg
Mj4mMQp0aW1lb3V0IC90IDEgL25vYnJlYWsgPm51bAp3c2NyaXB0LmV4ZSAiJX5k
cDBydW4taGlkZGVuLnZicyIgY29uZmlndXJhdGlvbgplY2hvIExlIHBvbnQgdG91
cm5lIG1haW50ZW5hbnQgZW4gYXJyaWVyZS1wbGFuLCBzYW5zIGZlbmV0cmUgdmlz
aWJsZS4KcGF1c2UK
-----END CERTIFICATE-----
:CONFIGURER_BAT_END
:RUN_HIDDEN_VBS_BEGIN
-----BEGIN CERTIFICATE-----
JyBMYW5jZSBsZSBwb250IFRQRSBCcmlkZ2Ugc2FucyBhdWN1bmUgZmVuZXRyZSB2
aXNpYmxlLiBVdGlsaXNlIHBhciBsZSBkb3NzaWVyDQonIERlbWFycmFnZSBkZSBX
aW5kb3dzLCBwYXIgbGUgbGllbiB0cGVicmlkZ2U6Ly9zdGFydCAoYm91dG9uICJD
b25uZWN0ZXIiKSBldA0KJyBwYXIgaW5zdGFsbC5iYXQvQ29uZmlndXJlci5iYXQu
DQonDQonIC0gTmUgbGFuY2UgSkFNQUlTIHVuIDJlIHBvbnQgc2kgdW4gdG91cm5l
IGRlamEgKGRldXggcG9udHMgPSB0aWNrZXRzIGltcHJpbWVzDQonICAgZW4gZG91
YmxlIDogaWxzIGludGVycm9nZW50IHRvdXMgbGVzIGRldXggbGUgc2VydmV1ciku
DQonIC0gRWNyaXQgdW5lIGxpZ25lIGRhbnMgJUFQUERBVEElXFRQRS1CcmlkZ2Vc
bGF1bmNoLmxvZyBhIGNoYXF1ZSBleGVjdXRpb24sDQonICAgYXZlYyBRVUkgbCdh
IGRlY2xlbmNoZWUgZXQgZGVwdWlzIGNvbWJpZW4gZGUgdGVtcHMgbGEgc2Vzc2lv
biBXaW5kb3dzIGVzdA0KJyAgIG91dmVydGUuIFVuIGxhbmNlbWVudCBhdXRvbWF0
aXF1ZSBhdSBkZW1hcnJhZ2UgdG9tYmUgZGFucyBsZXMgc2Vjb25kZXMgcXVpDQon
ICAgc3VpdmVudCBsJ291dmVydHVyZSBkZSBzZXNzaW9uIDsgdW4gY2xpYyBhcnJp
dmUgYmllbiBwbHVzIHRhcmQuDQpPcHRpb24gRXhwbGljaXQNCg0KRGltIHNoLCBm
c28NClNldCBzaCA9IENyZWF0ZU9iamVjdCgiV1NjcmlwdC5TaGVsbCIpDQpTZXQg
ZnNvID0gQ3JlYXRlT2JqZWN0KCJTY3JpcHRpbmcuRmlsZVN5c3RlbU9iamVjdCIp
DQoNClN1YiBKb3VybmFsKG1zZykNCiAgT24gRXJyb3IgUmVzdW1lIE5leHQNCiAg
RGltIGRvc3NpZXIsIGNoZW1pbiwgZg0KICBkb3NzaWVyID0gc2guRXhwYW5kRW52
aXJvbm1lbnRTdHJpbmdzKCIlQVBQREFUQSUiKSAmICJcVFBFLUJyaWRnZSINCiAg
SWYgTm90IGZzby5Gb2xkZXJFeGlzdHMoZG9zc2llcikgVGhlbiBmc28uQ3JlYXRl
Rm9sZGVyIGRvc3NpZXINCiAgY2hlbWluID0gZG9zc2llciAmICJcbGF1bmNoLmxv
ZyINCiAgSWYgZnNvLkZpbGVFeGlzdHMoY2hlbWluKSBUaGVuDQogICAgSWYgZnNv
LkdldEZpbGUoY2hlbWluKS5TaXplID4gMTAwMDAwIFRoZW4gZnNvLkRlbGV0ZUZp
bGUgY2hlbWluLCBUcnVlDQogIEVuZCBJZg0KICBTZXQgZiA9IGZzby5PcGVuVGV4
dEZpbGUoY2hlbWluLCA4LCBUcnVlKQ0KICBmLldyaXRlTGluZSBOb3cgJiAiICAi
ICYgbXNnDQogIGYuQ2xvc2UNCkVuZCBTdWINCg0KJyBRdWkgYSBsYW5jZSBjZSBz
Y3JpcHQgPyBMZSBmaWNoaWVyIGRlcG9zZSBkYW5zIGxlIGRvc3NpZXIgRGVtYXJy
YWdlIGRlIFdpbmRvd3MNCicgcydhcHBlbGxlIFRQRS1CcmlkZ2UudmJzIDsgbGVz
IGF1dHJlcyBhcHBlbGFudHMgcGFzc2VudCB1biBtb3QgZW4gYXJndW1lbnQNCicg
KGJvdXRvbiwgaW5zdGFsbGV1ciwgY29uZmlndXJhdGlvbikuIFNhbnMgcmllbiBk
ZSB0b3V0IGNlbGEgOiBsYW5jZSBhIGxhIG1haW4uDQpGdW5jdGlvbiBEZWNsZW5j
aGV1cigpDQogIERlY2xlbmNoZXVyID0gIm1hbnVlbCINCiAgSWYgTENhc2UoV1Nj
cmlwdC5TY3JpcHROYW1lKSA9ICJ0cGUtYnJpZGdlLnZicyIgVGhlbg0KICAgIERl
Y2xlbmNoZXVyID0gImRlbWFycmFnZSBXaW5kb3dzIChkb3NzaWVyIERlbWFycmFn
ZSkiDQogIEVsc2VJZiBXU2NyaXB0LkFyZ3VtZW50cy5Db3VudCA+IDAgVGhlbg0K
ICAgIERlY2xlbmNoZXVyID0gV1NjcmlwdC5Bcmd1bWVudHMoMCkNCiAgRW5kIElm
DQpFbmQgRnVuY3Rpb24NCg0KJyBTZWNvbmRlcyBlY291bGVlcyBkZXB1aXMgdW5l
IGRhdGUgYXUgZm9ybWF0IFdNSSAoIjIwMjYwOTI4MTQ1MDAyLjAwMDAwMCsxMjAi
KSwNCicgb3UgLTEgc2kgbGEgZGF0ZSBlc3QgaWxsaXNpYmxlLg0KRnVuY3Rpb24g
U2Vjb25kZXNEZXB1aXMoZGF0ZVdtaSkNCiAgRGltIGQNCiAgU2Vjb25kZXNEZXB1
aXMgPSAtMQ0KICBPbiBFcnJvciBSZXN1bWUgTmV4dA0KICBkID0gRGF0ZVNlcmlh
bChDSW50KE1pZChkYXRlV21pLCAxLCA0KSksIENJbnQoTWlkKGRhdGVXbWksIDUs
IDIpKSwgQ0ludChNaWQoZGF0ZVdtaSwgNywgMikpKSArIFRpbWVTZXJpYWwoQ0lu
dChNaWQoZGF0ZVdtaSwgOSwgMikpLCBDSW50KE1pZChkYXRlV21pLCAxMSwgMikp
LCBDSW50KE1pZChkYXRlV21pLCAxMywgMikpKQ0KICAnIFVuZSBkYXRlIFZCU2Ny
aXB0IGVzdCB1biBub21icmUgZGUgam91cnMgOiBsYSBkaWZmZXJlbmNlIHggODY0
MDAgPSBkZXMgc2Vjb25kZXMuDQogIElmIEVyci5OdW1iZXIgPSAwIFRoZW4gU2Vj
b25kZXNEZXB1aXMgPSBDTG5nKChOb3cgLSBkKSAqIDg2NDAwKQ0KRW5kIEZ1bmN0
aW9uDQoNCicgRGVwdWlzIGNvbWJpZW4gZGUgc2Vjb25kZXMgbGEgc2Vzc2lvbiBX
aW5kb3dzIGVzdCBvdXZlcnRlICgtMSBzaSBpbmNvbm51KS4NCicgT24gcHJlbmQg
bGUgcGx1cyBhbmNpZW4gZXhwbG9yZXIuZXhlIDogYydlc3QgbCdpbnRlcmZhY2Us
IGxhbmNlZSBhIGwnb3V2ZXJ0dXJlDQonIGRlIHNlc3Npb24uDQpGdW5jdGlvbiBT
ZWNvbmRlc0RlcHVpc091dmVydHVyZVNlc3Npb24oKQ0KICBEaW0gd21pLCBwcm9j
cywgcCwgZHMsIGJlc3QNCiAgYmVzdCA9IC0xDQogICcgTGEgdmFsZXVyIGRlIHJl
dG91ciBlc3QgZml4ZWUgQVZBTlQgdG91dGUgbGVjdHVyZSA6IHNpIFdpbmRvd3Mg
bidhIHBhcyBzb24NCiAgJyBzZXJ2aWNlIGQnaW5mb3JtYXRpb25zIHN5c3RlbWUg
KFdNSSkgb3Ugc2kgbGEgbGVjdHVyZSBlY2hvdWUgZW4gY291cnMgZGUNCiAgJyBy
b3V0ZSwgb24gcmVuZCAtMSAoaW5jb25udSkgYXUgbGlldSBkZSBuZSByaWVuIHJl
bmRyZS4NCiAgU2Vjb25kZXNEZXB1aXNPdXZlcnR1cmVTZXNzaW9uID0gLTENCiAg
T24gRXJyb3IgUmVzdW1lIE5leHQNCiAgU2V0IHdtaSA9IEdldE9iamVjdCgid2lu
bWdtdHM6XFwuXHJvb3RcY2ltdjIiKQ0KICBTZXQgcHJvY3MgPSB3bWkuRXhlY1F1
ZXJ5KCJTRUxFQ1QgQ3JlYXRpb25EYXRlIEZST00gV2luMzJfUHJvY2VzcyBXSEVS
RSBOYW1lID0gJ2V4cGxvcmVyLmV4ZSciKQ0KICBGb3IgRWFjaCBwIEluIHByb2Nz
DQogICAgZHMgPSBTZWNvbmRlc0RlcHVpcyhwLkNyZWF0aW9uRGF0ZSkNCiAgICBJ
ZiBkcyA+IGJlc3QgVGhlbg0KICAgICAgYmVzdCA9IGRzDQogICAgICBTZWNvbmRl
c0RlcHVpc091dmVydHVyZVNlc3Npb24gPSBiZXN0DQogICAgRW5kIElmDQogIE5l
eHQNCkVuZCBGdW5jdGlvbg0KDQpGdW5jdGlvbiBEdXJlZShzZWNzKQ0KICBJZiBJ
c0VtcHR5KHNlY3MpIE9yIE5vdCBJc051bWVyaWMoc2VjcykgVGhlbg0KICAgIER1
cmVlID0gImluY29ubnVlIg0KICBFbHNlSWYgc2VjcyA8IDAgVGhlbg0KICAgIER1
cmVlID0gImluY29ubnVlIg0KICBFbHNlSWYgc2VjcyA8IDE4MCBUaGVuDQogICAg
RHVyZWUgPSBzZWNzICYgIiBzIg0KICBFbHNlDQogICAgRHVyZWUgPSBJbnQoc2Vj
cyAvIDYwKSAmICIgbWluIg0KICBFbmQgSWYNCkVuZCBGdW5jdGlvbg0KDQpGdW5j
dGlvbiBQb250RGVqYUVuQ291cnMoKQ0KICBEaW0gd21pLCBwcm9jcywgcA0KICBQ
b250RGVqYUVuQ291cnMgPSBGYWxzZQ0KICBPbiBFcnJvciBSZXN1bWUgTmV4dA0K
ICBTZXQgd21pID0gR2V0T2JqZWN0KCJ3aW5tZ210czpcXC5ccm9vdFxjaW12MiIp
DQogIFNldCBwcm9jcyA9IHdtaS5FeGVjUXVlcnkoIlNFTEVDVCBDb21tYW5kTGlu
ZSBGUk9NIFdpbjMyX1Byb2Nlc3MgV0hFUkUgTmFtZSA9ICdub2RlLmV4ZSciKQ0K
ICBGb3IgRWFjaCBwIEluIHByb2NzDQogICAgSWYgTm90IElzTnVsbChwLkNvbW1h
bmRMaW5lKSBUaGVuDQogICAgICBJZiBJblN0cigxLCBwLkNvbW1hbmRMaW5lLCAi
dHBlLWJyaWRnZS13aW4uanMiLCB2YlRleHRDb21wYXJlKSA+IDAgVGhlbiBQb250
RGVqYUVuQ291cnMgPSBUcnVlDQogICAgRW5kIElmDQogIE5leHQNCkVuZCBGdW5j
dGlvbg0KDQpKb3VybmFsICJsYW5jZXVyIGV4ZWN1dGUgKGRlY2xlbmNoZXVyIDog
IiAmIERlY2xlbmNoZXVyKCkgJiAiLCBzZXNzaW9uIFdpbmRvd3Mgb3V2ZXJ0ZSBk
ZXB1aXMgIiAmIER1cmVlKFNlY29uZGVzRGVwdWlzT3V2ZXJ0dXJlU2Vzc2lvbigp
KSAmICIpIg0KSWYgUG9udERlamFFbkNvdXJzKCkgVGhlbg0KICBKb3VybmFsICJs
ZSBwb250IHRvdXJuZSBkZWphIC0gcmllbiBhIGZhaXJlIg0KRWxzZQ0KICAnIExl
ICIwIiA9IGZlbmV0cmUgY2FjaGVlLCBsZSAiRmFsc2UiID0gbmUgcGFzIGF0dGVu
ZHJlIChsZSBwb250IHRvdXJuZSBpbmRlZmluaW1lbnQpLg0KICBPbiBFcnJvciBS
ZXN1bWUgTmV4dA0KICBzaC5SdW4gQ2hyKDM0KSAmICJDOlxQcm9ncmFtIEZpbGVz
XG5vZGVqc1xub2RlLmV4ZSIgJiBDaHIoMzQpICYgIiAiICYgQ2hyKDM0KSAmICJD
OlxUUEUtQnJpZGdlXHRwZS1icmlkZ2Utd2luLmpzIiAmIENocigzNCksIDAsIEZh
bHNlDQogIElmIEVyci5OdW1iZXIgPD4gMCBUaGVuDQogICAgSm91cm5hbCAiRUNI
RUMgZHUgbGFuY2VtZW50IDogIiAmIEVyci5EZXNjcmlwdGlvbg0KICAgIEVyci5D
bGVhcg0KICBFbHNlDQogICAgSm91cm5hbCAicG9udCBsYW5jZSINCiAgRW5kIElm
DQogIE9uIEVycm9yIEdvVG8gMA0KRW5kIElmDQo=
-----END CERTIFICATE-----
:RUN_HIDDEN_VBS_END
